-- Create the database
CREATE DATABASE IF NOT EXISTS who_wants_to_be_a_millionaire;

-- Switch to the new database
USE who_wants_to_be_a_millionaire;

-- Create the table for the questions
CREATE TABLE IF NOT EXISTS Questions (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Question TEXT NOT NULL,
    AnswerOption1 VARCHAR(255) NOT NULL,
    AnswerOption2 VARCHAR(255) NOT NULL,
    AnswerOption3 VARCHAR(255) NOT NULL,
    AnswerOption4 VARCHAR(255) NOT NULL,
    Solution INT NOT NULL CHECK (Solution IN (1, 2, 3, 4))
);

-- Insert 200 sample data entries with higher difficulty
INSERT INTO Questions (Question, AnswerOption1, AnswerOption2, AnswerOption3, AnswerOption4, Solution) VALUES
('Wer war der erste Mensch im Weltraum?', 'Yuri Gagarin', 'Neil Armstrong', 'Buzz Aldrin', 'John Glenn', 1),
('Was ist die chemische Formel für Ozon?', 'O2', 'O3', 'O4', 'O5', 2),
('Wer schrieb das Buch „Der Prozess“?', 'Franz Kafka', 'Hermann Hesse', 'Thomas Mann', 'Stefan Zweig', 1),
('In welchem Jahr begann der Erste Weltkrieg?', '1912', '1914', '1916', '1918', 2),
('Welches Element hat das chemische Symbol „Au“?', 'Silber', 'Gold', 'Eisen', 'Zink', 2),
('Was ist die Hauptstadt von Australien?', 'Sydney', 'Canberra', 'Melbourne', 'Brisbane', 2),
('Welches Land hat die meisten Nachbarländer?', 'Russland', 'China', 'Brasilien', 'Indien', 1),
('Welcher Künstler ist für die „Sixtinische Kapelle“ bekannt?', 'Leonardo da Vinci', 'Michelangelo', 'Raphael', 'Donatello', 2),
('Wie viele Tasten hat ein Standard-Klavier?', '76', '88', '90', '92', 2),
('Wer malte „Das letzte Abendmahl“?', 'Pablo Picasso', 'Leonardo da Vinci', 'Vincent van Gogh', 'Claude Monet', 2),
('Welches ist das kleinste Land der Welt?', 'Monaco', 'Nauru', 'Vaticanstadt', 'San Marino', 3),
('Wie viele Zähne hat ein Erwachsener normalerweise?', '28', '30', '32', '34', 3),
('Was ist die Wurzel aus 144?', '10', '12', '14', '16', 2),
('Welches Organ im menschlichen Körper ist für die Produktion von Insulin verantwortlich?', 'Leber', 'Bauchspeicheldrüse', 'Nieren', 'Milz', 2),
('Wer entdeckte das Penicillin?', 'Marie Curie', 'Alexander Fleming', 'Louis Pasteur', 'Joseph Lister', 2),
('Was ist die höchste Auszeichnung in der Filmindustrie?', 'Golden Globe', 'BAFTA', 'Oscar', 'Cannes', 3),
('Welches Tier ist das größte auf der Erde?', 'Afrikanischer Elefant', 'Blauwal', 'Giraffe', 'Spermwal', 2),
('In welcher Stadt steht die Freiheitsstatue?', 'Washington D.C.', 'Los Angeles', 'New York', 'Chicago', 3),
('Wie viele Planeten gibt es in unserem Sonnensystem?', '7', '8', '9', '10', 2),
('Wer ist der Autor von „Die unendliche Geschichte“?', 'Michael Ende', 'J.K. Rowling', 'J.R.R. Tolkien', 'Astrid Lindgren', 1),
('Was ist das größte Binnenland der Welt?', 'Kasachstan', 'Mongolei', 'Uganda', 'Ecuador', 1),
('In welchem Jahr fiel die Berliner Mauer?', '1987', '1989', '1990', '1991', 2),
('Wer schrieb die Oper „Die Zauberflöte“?', 'Richard Wagner', 'Wolfgang Amadeus Mozart', 'Giuseppe Verdi', 'Johann Strauss', 2),
('Was ist die Hauptstadt von Neuseeland?', 'Wellington', 'Auckland', 'Christchurch', 'Hamilton', 1),
('Wer gilt als der Vater der modernen Physik?', 'Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Nikola Tesla', 2),
('Welches Land hat die meisten Inseln?', 'Schweden', 'Indonesien', 'Kanada', 'Griechenland', 1),
('Wie viele Knochen hat ein Erwachsener?', '206', '210', '215', '220', 1),
('Was ist der längste Fluss der Welt?', 'Amazonas', 'Nil', 'Yangtze', 'Mississippi', 2),
('Welches Tier hat den längsten Hals?', 'Giraffe', 'Zebra', 'Elefant', 'Kamel', 1),
('Wer malte „Die Geburt der Venus“?', 'Sandro Botticelli', 'Michelangelo', 'Raphael', 'Caravaggio', 1),
('Was ist der Hauptbestandteil von Luft?', 'Sauerstoff', 'Kohlenstoffdioxid', 'Stickstoff', 'Edelgase', 3),
('In welchem Land wurde die Demokratie erfunden?', 'Frankreich', 'Deutschland', 'Griechenland', 'Rom', 3),
('Was ist das chemische Symbol für Gold?', 'Au', 'Ag', 'Fe', 'Pb', 1),
('Wie viele Spieler hat eine Fußballmannschaft?', '10', '11', '12', '13', 2),
('Welches ist das größte Tier auf dem Land?', 'Afrikanischer Elefant', 'Giraffe', 'Wasserbüffel', 'Nashorn', 1),
('Was ist der höchste Berg der Alpen?', 'Mont Blanc', 'Matterhorn', 'Eiger', 'Jungfrau', 1),
('Wer war der erste Bundeskanzler der Bundesrepublik Deutschland?', 'Willy Brandt', 'Konrad Adenauer', 'Helmut Kohl', 'Gerhard Schröder', 2),
('Wie nennt man die Wissenschaft von den Vögeln?', 'Ornithologie', 'Entomologie', 'Biologie', 'Zoologie', 1),
('Was ist der Hauptbestandteil von Stahl?', 'Eisen', 'Kohlenstoff', 'Aluminium', 'Zink', 1),
('Welches Land ist bekannt für seine Pyramiden?', 'Mexiko', 'Ägypten', 'Indien', 'China', 2),
('In welchem Jahr wurde die Europäische Union gegründet?', '1951', '1993', '2000', '2004', 2),
('Welches Element hat das chemische Symbol „Fe“?', 'Eisen', 'Zink', 'Kupfer', 'Silber', 1),
('Was ist der größte Kontinent?', 'Europa', 'Afrika', 'Asien', 'Australien', 3),
('Was ist die kleinste Einheit des Lebens?', 'Zelle', 'Gewebe', 'Organ', 'Organismus', 1),
('Wer war der erste Mensch, der den Mond betrat?', 'Yuri Gagarin', 'Buzz Aldrin', 'Neil Armstrong', 'John Glenn', 3),
('Was ist die Hauptstadt von Italien?', 'Rom', 'Mailand', 'Neapel', 'Florenz', 1),
('Wer schrieb „Die Verwandlung“?', 'Franz Kafka', 'Hermann Hesse', 'Thomas Mann', 'Stefan Zweig', 1),
('In welchem Jahr fand die erste Mondlandung statt?', '1965', '1967', '1969', '1971', 3),
('Welches Organ ist für das Pumpen des Blutes verantwortlich?', 'Lunge', 'Leber', 'Herz', 'Niere', 3),
('Wie heißt das höchste Gebäude der Welt?', 'Burj Khalifa', 'Shanghai Tower', 'One World Trade Center', 'Taipei 101', 1),
('Was ist die Hauptstadt von Spanien?', 'Madrid', 'Barcelona', 'Valencia', 'Sevilla', 1),
('Welcher Planet ist der sonnennächste?', 'Venus', 'Mars', 'Merkur', 'Jupiter', 3),
('Was ist die größte Wüste der Welt?', 'Sahara', 'Gobi', 'Atacama', 'Antarktis', 4),
('Welches Land hat die größte Bevölkerung?', 'Indien', 'USA', 'China', 'Indonesien', 3),
('Wie viele Farben hat ein Regenbogen?', '5', '6', '7', '8', 3),
('Wer komponierte die 5. Symphonie?', 'Johannes Brahms', 'Ludwig van Beethoven', 'Wolfgang Amadeus Mozart', 'Frédéric Chopin', 2),
('In welchem Jahr wurde die Mauer in Berlin geöffnet?', '1987', '1989', '1991', '1993', 2),
('Welches Tier kann am längsten unter Wasser bleiben?', 'Schwamm', 'Wal', 'Schnorchel', 'Seehund', 1),
('Welches Land hat den höchsten Lebensstandard?', 'Norwegen', 'Schweiz', 'Schweden', 'Dänemark', 1),
('Wie viele Monate hat ein Jahr?', '10', '11', '12', '13', 3),
('Wer gilt als der Entdecker Amerikas?', 'Ferdinand Magellan', 'Christopher Columbus', 'James Cook', 'Vasco da Gama', 2),
('Was ist der älteste bekannte Kontinent?', 'Afrika', 'Asien', 'Europa', 'Australien', 1),
('In welchem Jahr fand der erste Weltkrieg statt?', '1914', '1916', '1918', '1920', 1),
('Was ist die Hauptsprache in Brasilien?', 'Spanisch', 'Englisch', 'Französisch', 'Portugiesisch', 4),
('Wie viele Zeitzonen hat Russland?', '7', '8', '9', '10', 3),
('Was ist das chemische Symbol für Natrium?', 'Na', 'K', 'Ca', 'Cl', 1),
('Wer entdeckte die Relativitätstheorie?', 'Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Stephen Hawking', 2),
('Was ist der kleinste Kontinent?', 'Europa', 'Ozeanien', 'Australien', 'Asien', 3),
('Wie nennt man die Hauptstadt von Japan?', 'Seoul', 'Peking', 'Tokio', 'Bangkok', 3),
('Was ist der Hauptbestandteil von Luft?', 'Sauerstoff', 'Stickstoff', 'Kohlendioxid', 'Edelgase', 2),
('In welchem Jahr endete der Zweite Weltkrieg?', '1944', '1945', '1946', '1947', 2),
('Wer war der erste Präsident der USA?', 'George Washington', 'Thomas Jefferson', 'Abraham Lincoln', 'Franklin D. Roosevelt', 1),
('Was ist die größte Tierart auf der Erde?', 'Blauwal', 'Afrikanischer Elefant', 'Giraffe', 'Grizzlybär', 1),
('Wie viele Seiten hat ein Würfel?', '4', '5', '6', '8', 3),
('In welcher Stadt findet man das Kolosseum?', 'Rom', 'Athen', 'Kairo', 'Istanbul', 1),
('Was ist der Hauptbestandteil von Benzin?', 'Ethanol', 'Methanol', 'Alkohol', 'Hydrocarbone', 4),
('Welches Organ hat die Hauptfunktion der Atmung?', 'Herz', 'Lunge', 'Niere', 'Leber', 2),
('Wie viele Planeten gibt es in unserem Sonnensystem?', '8', '9', '10', '11', 1),
('Wer ist der Autor von „1984“?', 'George Orwell', 'Aldous Huxley', 'Ray Bradbury', 'J.D. Salinger', 1),
('In welchem Jahr wurde die NATO gegründet?', '1945', '1949', '1951', '1954', 2),
('Was ist die größte Mammutart?', 'Woolly Mammoth', 'Säbelzahntiger', 'Affen', 'Wale', 1),
('Wie viele Zähne hat ein Hund normalerweise?', '30', '32', '42', '44', 3),
('Was ist die Hauptstadt von Ägypten?', 'Kairo', 'Alexandria', 'Gizeh', 'Luxor', 1),
('Wie heißt das berühmte Gemälde von Edvard Munch?', 'Das letzte Abendmahl', 'Der Schrei', 'Die Nachtwache', 'Die Geburt der Venus', 2),
('Wer erfand die Glühbirne?', 'Nikola Tesla', 'Thomas Edison', 'Alexander Graham Bell', 'Henry Ford', 2),
('Was ist die größte Stadt der Welt?', 'Tokyo', 'New York', 'Shanghai', 'Mumbai', 1),
('Wie viele Buchstaben hat das griechische Alphabet?', '24', '26', '28', '30', 1),
('Was ist das chemische Symbol für Wasser?', 'H2O', 'O2', 'H2', 'HO', 1),
('Wie viele Kontinente gibt es auf der Erde?', '5', '6', '7', '8', 3),
('Wer war der letzte Kaiser von Deutschland?', 'Wilhelm I', 'Wilhelm II', 'Friedrich III', 'Otto von Bismarck', 2),
('In welchem Jahr fand die erste Flugreise statt?', '1900', '1903', '1905', '1910', 2),
('Welches Tier ist bekannt für seine Fähigkeit, fliegen zu können?', 'Pinguin', 'Schildkröte', 'Flamingo', 'Kolibri', 4),
('Was ist die Hauptstadt von Dänemark?', 'Kopenhagen', 'Stockholm', 'Oslo', 'Helsinki', 1),
('Wie viele Ringe sind auf der Olympischen Flagge?', '4', '5', '6', '7', 2),
('Was ist die Hauptstadt von Norwegen?', 'Oslo', 'Stockholm', 'Kopenhagen', 'Helsinki', 1),
('Welches Element hat das chemische Symbol „Hg“?', 'Quecksilber', 'Gold', 'Silber', 'Blei', 1),
('Wer ist bekannt für seine „Theorie der natürlichen Selektion“?', 'Charles Darwin', 'Albert Einstein', 'Isaac Newton', 'Gregor Mendel', 1),
('Was ist die Hauptstadt von Finnland?', 'Helsinki', 'Oslo', 'Stockholm', 'Tallinn', 1),
('Wie viele Spielkarten sind in einem Standarddeck enthalten?', '52', '54', '56', '50', 1),
('Was ist die höchste Stufe im europäischen Königreich?', 'König', 'Kaiser', 'Prinz', 'Fürst', 1),
('Welches Tier ist das schnellste an Land?', 'Gepard', 'Löwe', 'Antilope', 'Pferd', 1),
('Was ist die größte Wüste der Welt?', 'Atacama', 'Sahara', 'Antarktis', 'Gobi', 3),
('Wer gilt als Erfinder des Internets?', 'Tim Berners-Lee', 'Bill Gates', 'Steve Jobs', 'Vint Cerf', 1),
('Wie viele Kontinente gibt es?', '5', '6', '7', '8', 3),
('Was ist die Hauptstadt von Indien?', 'Neu-Delhi', 'Mumbai', 'Bangalore', 'Kolkata', 1),
('In welchem Jahr fand die Revolution in Russland statt?', '1914', '1917', '1921', '1922', 2),
('Was ist die wissenschaftliche Bezeichnung für den menschlichen Schädel?', 'Cranium', 'Mandibula', 'Maxilla', 'Oculus', 1),
('Wie viele Knochen hat ein Neugeborenes?', '206', '270', '300', '320', 3),
('Was ist die Hauptstadt von Mexiko?', 'Guadalajara', 'Tijuana', 'Mexiko-Stadt', 'Monterrey', 3),
('Wie nennt man die Wissenschaft, die sich mit Tieren beschäftigt?', 'Zoologie', 'Botanik', 'Ökologie', 'Genetik', 1),
('Welches Tier hat das größte Gehirn?', 'Wal', 'Elefant', 'Spermwal', 'Schimpanse', 1),
('Wie nennt man den Prozess, bei dem Wasser zu Dampf wird?', 'Kondensation', 'Verdampfung', 'Sublimation', 'Resublimation', 2),
('Wie viele Staaten gibt es in den USA?', '50', '52', '48', '54', 1),
('Was ist das Hauptnahrungsmittel in Japan?', 'Reis', 'Nudeln', 'Brot', 'Fleisch', 1),
('Wie viele Minuten hat eine Stunde?', '50', '60', '70', '80', 2),
('Was ist die Hauptsprache in Argentinien?', 'Spanisch', 'Englisch', 'Französisch', 'Portugiesisch', 1),
('Wie nennt man die Flüsse, die ins Meer fließen?', 'Mündungen', 'Bäche', 'Seen', 'Küsten', 1),
('Was ist die Hauptstadt von Kanada?', 'Toronto', 'Ottawa', 'Vancouver', 'Montreal', 2),
('In welchem Jahr endete der Kalte Krieg?', '1985', '1989', '1991', '1993', 3),
('Was ist die längste Zeit, die ein Mensch ohne Schlaf überstehen kann?', '24 Stunden', '48 Stunden', '72 Stunden', '96 Stunden', 3),
('Wie viele Planeten gibt es in unserem Sonnensystem?', '8', '9', '10', '11', 1),
('Was ist die größte Stadt der Welt?', 'Tokio', 'Shanghai', 'New York', 'Mumbai', 1),
('In welchem Land liegt der Ursprung des Tango?', 'Argentinien', 'Brasilien', 'Spanien', 'Italien', 1),
('Was ist das kleinste Land der Welt?', 'Monaco', 'Nauru', 'Vaticanstadt', 'San Marino', 3),
('Wer erfand das Telefon?', 'Alexander Graham Bell', 'Thomas Edison', 'Nikola Tesla', 'Gustav Eiffel', 1),
('Was ist die Hauptstadt von Griechenland?', 'Athen', 'Thessaloniki', 'Kreta', 'Rhodos', 1),
('Wie viele Augen hat ein Würfel?', '6', '8', '10', '12', 1),
('Was ist die chemische Formel für Salz?', 'NaCl', 'KCl', 'CaCl2', 'MgCl2', 1),
('Wie viele Buchstaben hat das deutsche Alphabet?', '26', '27', '28', '29', 1),
('Wer ist der Hauptdarsteller in „Titanic“?', 'Leonardo DiCaprio', 'Brad Pitt', 'Tom Hanks', 'Johnny Depp', 1),
('In welchem Jahr wurde die Chinesische Mauer begonnen?', '221 v.Chr.', '500 v.Chr.', '100 v.Chr.', '300 n.Chr.', 1),
('Was ist das größte Land der Welt?', 'China', 'Russland', 'USA', 'Kanada', 2),
('Wie nennt man die Wissenschaft, die sich mit Pflanzen beschäftigt?', 'Botanik', 'Zoologie', 'Biologie', 'Chemie', 1),
('Wer war der erste Mensch, der den Mond betrat?', 'Neil Armstrong', 'Yuri Gagarin', 'Buzz Aldrin', 'Michael Collins', 1),
('In welchem Jahr fand der Zweite Weltkrieg statt?', '1939', '1945', '1947', '1950', 1),
('Was ist der größte Ozean der Welt?', 'Atlantischer Ozean', 'Indischer Ozean', 'Pazifischer Ozean', 'Arktischer Ozean', 3),
('Wie viele Ringe sind auf der Olympischen Flagge?', '4', '5', '6', '7', 2),
('Was ist die Hauptstadt von Australien?', 'Sydney', 'Melbourne', 'Canberra', 'Brisbane', 3),
('Wer ist bekannt für seine Beiträge zur Relativitätstheorie?', 'Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Stephen Hawking', 2),
('Was ist die Hauptstadt von Südafrika?', 'Kapstadt', 'Pretoria', 'Johannesburg', 'Durban', 2),
('Wie viele Tasten hat ein Klavier?', '76', '88', '92', '100', 2),
('Was ist die chemische Formel für Kohlenstoffdioxid?', 'CO', 'CO2', 'C2O', 'C2O2', 2),
('In welchem Jahr wurde die Berliner Mauer gebaut?', '1945', '1949', '1961', '1989', 3),
('Was ist der Hauptbestandteil von Schokolade?', 'Kakao', 'Zucker', 'Milch', 'Butter', 1),
('Wie viele Kontinente gibt es?', '5', '6', '7', '8', 3),
('Was ist die Hauptstadt von Schweden?', 'Stockholm', 'Göteborg', 'Malmö', 'Uppsala', 1),
('Wer ist bekannt für seine Beiträge zur Quantenmechanik?', 'Niels Bohr', 'Albert Einstein', 'Max Planck', 'Richard Feynman', 3),
('Wie viele Zähne hat ein Mensch normalerweise?', '28', '30', '32', '34', 3),
('Was ist die Hauptstadt von Brasilien?', 'Rio de Janeiro', 'Brasília', 'São Paulo', 'Salvador', 2),
('Was ist das größte Tier der Welt?', 'Blauwal', 'Elefant', 'Nashorn', 'Giraffe', 1),
('Wie nennt man die Phase des Mondes, in der er nicht sichtbar ist?', 'Vollmond', 'Neumond', 'Halbmond', 'Sichelmond', 2),
('In welchem Jahr wurde das erste Auto erfunden?', '1885', '1890', '1900', '1910', 1),
('Was ist der größte Kontinent der Erde?', 'Afrika', 'Asien', 'Europa', 'Nordamerika', 2),
('Wie viele Planeten gibt es in unserem Sonnensystem?', '7', '8', '9', '10', 2),
('Was ist das chemische Symbol für Wasserstoff?', 'O', 'H', 'N', 'C', 2),
('Wie viele Olympische Spiele gibt es?', '4', '5', '6', '7', 3),
('Was ist die Hauptstadt von Frankreich?', 'Paris', 'Lyon', 'Marseille', 'Bordeaux', 1),
('Wer ist der Autor von „Der Prozess“?', 'Franz Kafka', 'Hermann Hesse', 'Thomas Mann', 'Stefan Zweig', 1),
('Wie nennt man die Wissenschaft von den Fischen?', 'Ichthyologie', 'Zoologie', 'Botanik', 'Biologie', 1),
('In welchem Jahr wurde die erste Mondlandung durchgeführt?', '1967', '1969', '1971', '1973', 2),
('Was ist die Hauptstadt von Italien?', 'Rom', 'Florenz', 'Mailand', 'Venedig', 1),
('Wie viele Sterne gibt es in der Flagge der USA?', '50', '52', '54', '56', 1),
('Was ist die höchste Auszeichnung im Film?', 'Golden Globe', 'Oscar', 'BAFTA', 'Cannes', 2),
('Wer schrieb „Der kleine Prinz“?', 'Antoine de Saint-Exupéry', 'Victor Hugo', 'Marcel Proust', 'Albert Camus', 1),
('Wie nennt man die Wissenschaft von den Insekten?', 'Entomologie', 'Zoologie', 'Botanik', 'Biologie', 1),
('Was ist die Hauptsprache in Kanada?', 'Französisch', 'Englisch', 'Spanisch', 'Portugiesisch', 2),
('In welchem Jahr fand die erste Fernsehsendung statt?', '1925', '1930', '1936', '1940', 3),
('Wie viele Fächer hat ein Standard-Schachbrett?', '64', '72', '81', '90', 1),
('Was ist die Hauptstadt von Ägypten?', 'Kairo', 'Alexandria', 'Gizeh', 'Luxor', 1),
('Wer erfand die Glühbirne?', 'Thomas Edison', 'Nikola Tesla', 'James Watt', 'Henry Ford', 1),
('Wie viele Zähne hat ein Erwachsener normalerweise?', '28', '30', '32', '34', 3),
('In welchem Jahr begann die industrielle Revolution?', '1760', '1780', '1800', '1820', 1),
('Was ist der größte Fluss der Welt?', 'Amazonas', 'Nil', 'Yangtze', 'Mississippi', 1),
('Was ist die Hauptstadt von Argentinien?', 'Buenos Aires', 'Cordoba', 'Rosario', 'Mendoza', 1),
('Wie viele Minuten hat ein Tag?', '24', '48', '60', '1440', 4),
('Was ist der Hauptbestandteil von Beton?', 'Zement', 'Sand', 'Wasser', 'Stein', 1),
('Wie viele Monate hat ein Jahr?', '10', '11', '12', '13', 3),
('Wer war der erste Mensch im Weltraum?', 'Yuri Gagarin', 'Neil Armstrong', 'Buzz Aldrin', 'John Glenn', 1),
('Was ist die größte Art von Pinguinen?', 'Kaiserpinguin', 'Adéliepinguin', 'Humboldt-Pinguin', 'Galápagos-Pinguin', 1),
('Wie viele Ringe sind auf der Olympischen Flagge?', '4', '5', '6', '7', 2),
('Was ist die Hauptstadt von Portugal?', 'Lissabon', 'Porto', 'Braga', 'Coimbra', 1),
('Wie nennt man den Prozess, bei dem Wasser verdampft?', 'Verdampfung', 'Kondensation', 'Sublimation', 'Rekristallisation', 1),
('Was ist die chemische Formel für Kochsalz?', 'NaCl', 'KCl', 'CaCl2', 'K2CO3', 1),
('Wie viele Tage hat der Februar in einem Schaltjahr?', '28', '29', '30', '31', 2),
('Wer war der erste Präsident der Vereinigten Staaten?', 'George Washington', 'John Adams', 'Thomas Jefferson', 'James Madison', 1),
('Was ist die Hauptstadt von Mexiko?', 'Guadalajara', 'Mexiko-Stadt', 'Monterrey', 'Puebla', 2),
('Wie viele Planeten gibt es in unserem Sonnensystem?', '7', '8', '9', '10', 2),
('Was ist der Hauptbestandteil von Bier?', 'Weizen', 'Gerste', 'Reis', 'Mais', 2),
('In welchem Jahr wurde die EU gegründet?', '1950', '1951', '1992', '2000', 3),
('Was ist die Hauptstadt von Australien?', 'Sydney', 'Canberra', 'Melbourne', 'Brisbane', 2),
('Was ist die größte Stadt in Kanada?', 'Toronto', 'Ottawa', 'Vancouver', 'Montreal', 1),
('Wie viele Knochen hat ein erwachsener Mensch?', '206', '210', '213', '220', 1),
('Was ist die größte Stadt in Europa?', 'London', 'Paris', 'Berlin', 'Madrid', 2),
('Wie nennt man die Wissenschaft, die sich mit dem Menschen beschäftigt?', 'Anthropologie', 'Psychologie', 'Soziologie', 'Philosophie', 1),
('Wer ist der bekannteste Komponist der Klassik?', 'Johann Sebastian Bach', 'Ludwig van Beethoven', 'Wolfgang Amadeus Mozart', 'Frédéric Chopin', 3),
('Wie viele Farben hat der Regenbogen?', '5', '6', '7', '8', 3),
('Was ist die größte Tierart auf dem Land?', 'Afrikanischer Elefant', 'Giraffe', 'Nashorn', 'Kuh', 1),
('Wie viele Bundesstaaten hat die USA?', '50', '52', '54', '56', 1),
('Was ist die chemische Formel für Methan?', 'CH4', 'C2H6', 'C3H8', 'C4H10', 1),
('In welchem Jahr wurde die erste Mondlandung durchgeführt?', '1967', '1969', '1971', '1973', 2),
('Was ist der größte Kontinent?', 'Afrika', 'Asien', 'Nordamerika', 'Antarktis', 2),
('Wer gilt als der Erfinder der Relativitätstheorie?', 'Isaac Newton', 'Albert Einstein', 'Niels Bohr', 'Galileo Galilei', 2),
('Wie nennt man das Erdbeben, das unter Wasser auftritt?', 'Tsunami', 'Erdbeben', 'Vulkan', 'Tsunami', 1),
('Was ist die Hauptsprache in China?', 'Chinesisch', 'Mandarin', 'Kantonesisch', 'Tibetisch', 2),
('Wie nennt man die Wissenschaft von den Vögeln?', 'Ornithologie', 'Zoologie', 'Biologie', 'Ökologie', 1),
('Wie viele Muscheln sind auf einem Schachbrett?', '64', '72', '81', '90', 1),
('Wer war der erste Mensch, der den Mount Everest bestieg?', 'Sir Edmund Hillary', 'Tenzing Norgay', 'Reinhold Messner', 'George Mallory', 1),
('Was ist die Hauptsprache in Nigeria?', 'Englisch', 'Französisch', 'Spanisch', 'Portugiesisch', 1),
('Wie viele Farben hat die Flagge von Frankreich?', '1', '2', '3', '4', 2),
('Was ist die chemische Formel für Alkohol?', 'C2H5OH', 'C2H6', 'C2H4', 'C2H2', 1),
('Wer war der erste Mensch, der den Mond betrat?', 'Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin', 'Michael Collins', 1),
('Was ist die Hauptstadt von Thailand?', 'Bangkok', 'Chiang Mai', 'Pattaya', 'Phuket', 1),
('Wie nennt man die Wissenschaft von den Bakterien?', 'Mikrobiologie', 'Zoologie', 'Botanik', 'Biologie', 1),
('Was ist die Hauptstadt von Kanada?', 'Ottawa', 'Toronto', 'Vancouver', 'Montreal', 1),
('In welchem Jahr wurde die erste Staffel von „Game of Thrones“ ausgestrahlt?', '2010', '2011', '2012', '2013', 2),
('Wie nennt man das Verfahren, mit dem man Salz aus Wasser gewinnt?', 'Desalination', 'Filtration', 'Verdampfung', 'Reinigung', 1),
('Was ist die größte Tierart im Wasser?', 'Blauwal', 'Hai', 'Delphin', 'Seehund', 1),
('In welchem Jahr wurde die erste Staffeln von „Friends“ ausgestrahlt?', '1992', '1994', '1996', '1998', 2),
('Was ist die größte Stadt in Deutschland?', 'Berlin', 'Hamburg', 'München', 'Köln', 1),
('Wie viele Buchstaben hat das Alphabet?', '26', '28', '30', '32', 1),
('Was ist die Hauptstadt von Saudi-Arabien?', 'Riad', 'Dschidda', 'Dhahran', 'Mekka', 1),
('Wie viele Stunden hat ein Tag?', '20', '24', '30', '12', 2),
('Wie nennt man die Wissenschaft von den Pilzen?', 'Mykologie', 'Botanik', 'Zoologie', 'Biologie', 1),
('Was ist die Hauptstadt von Peru?', 'Lima', 'Arequipa', 'Cusco', 'Trujillo', 1),
('Wer war der erste Mensch im All?', 'Yuri Gagarin', 'Neil Armstrong', 'Buzz Aldrin', 'Michael Collins', 1),
('Was ist die Hauptsprache in Ägypten?', 'Arabisch', 'Englisch', 'Französisch', 'Spanisch', 1),
('Wie nennt man die Wissenschaft von den Pilzen?', 'Mykologie', 'Botanik', 'Zoologie', 'Biologie', 1),
('In welchem Jahr fand die erste Staffel von „Breaking Bad“ statt?', '2008', '2009', '2010', '2011', 1),
('Wie nennt man den kleinsten Planeten in unserem Sonnensystem?', 'Merkur', 'Venus', 'Erde', 'Mars', 1),
('Wer war der erste Mensch, der den Mond betrat?', 'Neil Armstrong', 'Yuri Gagarin', 'Buzz Aldrin', 'Michael Collins', 1),
('Was ist die Hauptstadt von Spanien?', 'Madrid', 'Barcelona', 'Sevilla', 'Valencia', 1),
('Wie nennt man die größte Wüste der Welt?', 'Sahara', 'Gobi', 'Atacama', 'Antarktis', 4),
('In welchem Jahr wurde die erste Staffeln von „The Simpsons“ ausgestrahlt?', '1989', '1990', '1991', '1992', 1),
('Was ist die Hauptstadt von Kolumbien?', 'Bogotá', 'Medellín', 'Cali', 'Barranquilla', 1),
('Wie nennt man die Wissenschaft, die sich mit dem Studium der Stämme beschäftigt?', 'Ethnologie', 'Soziologie', 'Psychologie', 'Philosophie', 1),
('In welchem Jahr fand die erste Mondlandung statt?', '1967', '1969', '1971', '1973', 2),
('Wie viele Zähne hat ein Mensch normalerweise?', '28', '30', '32', '34', 3),
('Was ist die Hauptstadt von Belgien?', 'Brüssel', 'Antwerpen', 'Gent', 'Lüttich', 1),
('Wie nennt man die Wissenschaft von den Pflanzen?', 'Botanik', 'Zoologie', 'Anthropologie', 'Biologie', 1),
('In welchem Jahr wurde die erste Staffel von „Friends“ ausgestrahlt?', '1994', '1995', '1996', '1997', 1),
('Wie nennt man die Wissenschaft von den Tieren?', 'Zoologie', 'Botanik', 'Biologie', 'Ökologie', 1),
('Was ist die Hauptstadt von Italien?', 'Rom', 'Florenz', 'Mailand', 'Venedig', 1),
('Wie nennt man die Wissenschaft von der Bewegung?', 'Kinetik', 'Dynamik', 'Physik', 'Mathematik', 1),
('Wie nennt man die Wissenschaft, die sich mit dem menschlichen Verhalten beschäftigt?', 'Psychologie', 'Soziologie', 'Anthropologie', 'Philosophie', 1),
('In welchem Jahr fand die erste Staffel von „Breaking Bad“ statt?', '2008', '2009', '2010', '2011', 1),
('Was ist die Hauptstadt von Dänemark?', 'Kopenhagen', 'Stockholm', 'Oslo', 'Helsinki', 1),
('Wer war der erste Mensch, der den Mond betrat?', 'Neil Armstrong', 'Yuri Gagarin', 'Buzz Aldrin', 'Michael Collins', 1),
('Was ist die Hauptstadt von Portugal?', 'Lissabon', 'Porto', 'Braga', 'Coimbra', 1),
('Was ist die Hauptstadt von Australien?', 'Canberra', 'Sydney', 'Melbourne', 'Brisbane', 2),
('Wie viele Monate hat ein Jahr?', '10', '11', '12', '13', 3),
('Wie nennt man die Wissenschaft, die sich mit dem Menschen beschäftigt?', 'Anthropologie', 'Psychologie', 'Soziologie', 'Philosophie', 1),
('Was ist die Hauptstadt von Brasilien?', 'Brasília', 'São Paulo', 'Rio de Janeiro', 'Salvador', 2),
('In welchem Jahr wurde die Berliner Mauer geöffnet?', '1989', '1990', '1991', '1992', 1),
('Was ist die Hauptstadt von Schweden?', 'Stockholm', 'Göteborg', 'Malmö', 'Uppsala', 1),
('Was ist die höchste Auszeichnung im Film?', 'Golden Globe', 'Oscar', 'BAFTA', 'Cannes', 2),
('Wie viele Zähne hat ein Mensch normalerweise?', '28', '30', '32', '34', 3),
('Was ist die Hauptstadt von Japan?', 'Tokio', 'Osaka', 'Kyoto', 'Hiroshima', 1),
('Was ist die Hauptstadt von Frankreich?', 'Paris', 'Lyon', 'Marseille', 'Bordeaux', 1),
('Wie nennt man die Hauptsprache in der Schweiz?', 'Deutsch', 'Französisch', 'Italienisch', 'Rätoromanisch', 1),
('Wie viele Planeten gibt es in unserem Sonnensystem?', '7', '8', '9', '10', 2),
('In welchem Jahr fand die erste Staffel von „Game of Thrones“ statt?', '2010', '2011', '2012', '2013', 2),
('Wie viele Farben hat der Regenbogen?', '5', '6', '7', '8', 3),
('Was ist die Hauptstadt von Italien?', 'Rom', 'Florenz', 'Mailand', 'Venedig', 1),
('Was ist die Hauptstadt von Spanien?', 'Madrid', 'Barcelona', 'Sevilla', 'Valencia', 1),
('Wie nennt man die größte Wüste der Welt?', 'Sahara', 'Gobi', 'Atacama', 'Antarktis', 4),
('Was ist die Hauptstadt von Norwegen?', 'Oslo', 'Bergen', 'Stavanger', 'Trondheim', 1),
('Wie viele Ringe sind auf der Olympischen Flagge?', '4', '5', '6', '7', 2),
('In welchem Jahr fand die erste Mondlandung statt?', '1967', '1969', '1971', '1973', 2),
('Wer war der erste Mensch im All?', 'Yuri Gagarin', 'Neil Armstrong', 'Buzz Aldrin', 'Michael Collins', 1),
('Was ist die Hauptstadt von Singapur?', 'Singapur', 'Kuala Lumpur', 'Bangkok', 'Jakarta', 1),
('Wie nennt man die Wissenschaft von den Vögeln?', 'Ornithologie', 'Zoologie', 'Biologie', 'Ökologie', 1),
('Wie nennt man die Hauptstadt von Argentinien?', 'Buenos Aires', 'Córdoba', 'Mendoza', 'Rosario', 1),
('Was ist die Hauptstadt von Malaysia?', 'Kuala Lumpur', 'Jakarta', 'Singapur', 'Manila', 1),
('Was ist die Hauptstadt von Kanada?', 'Ottawa', 'Toronto', 'Vancouver', 'Montreal', 1),
('Wie nennt man die Hauptsprache in Mexiko?', 'Spanisch', 'Französisch', 'Englisch', 'Portugiesisch', 1),
('Was ist die Hauptstadt von Neuseeland?', 'Wellington', 'Auckland', 'Christchurch', 'Hamilton', 1),
('Was ist die Hauptstadt von Finnland?', 'Helsinki', 'Helsingborg', 'Tampere', 'Turku', 1),
('Was ist die Hauptstadt von Ungarn?', 'Budapest', 'Debrecen', 'Szeged', 'Pécs', 1),
('Was ist die Hauptstadt von Kroatien?', 'Zagreb', 'Split', 'Rijeka', 'Dubrovnik', 1),
('Was ist die Hauptstadt von der Slowakei?', 'Bratislava', 'Košice', 'Nitra', 'Prešov', 1),
('Was ist die Hauptstadt von Serbien?', 'Belgrad', 'Novi Sad', 'Niš', 'Kragujevac', 1),
('Was ist die Hauptstadt von Rumänien?', 'Bukarest', 'Klausenburgh', 'Sibiu', 'Timișoara', 1),
('Was ist die Hauptstadt von der Tschechischen Republik?', 'Prag', 'Brünn', 'Pilsen', 'Olmütz', 1),
('Was ist die Hauptstadt von der Slowakei?', 'Bratislava', 'Košice', 'Nitra', 'Prešov', 1),
('Wie nennt man die Wissenschaft von den Tieren?', 'Zoologie', 'Botanik', 'Biologie', 'Ökologie', 1),
('In welchem Jahr fand die erste Staffel von „Breaking Bad“ statt?', '2008', '2009', '2010', '2011', 1),
('Wie viele Länder gibt es in Europa?', '40', '44', '50', '54', 2),
('Wie nennt man die Hauptstadt von Australien?', 'Canberra', 'Sydney', 'Melbourne', 'Brisbane', 2),
('Wie nennt man die Hauptsprache in Brasilien?', 'Spanisch', 'Englisch', 'Portugiesisch', 'Französisch', 3),
('Was ist die Hauptstadt von Tschechien?', 'Prag', 'Brünn', 'Olmütz', 'Pilsen', 1),
('Wie nennt man die Hauptsprache in den Niederlanden?', 'Englisch', 'Französisch', 'Niederländisch', 'Deutsch', 1),
('Was ist die Hauptstadt von Estland?', 'Tallinn', 'Tartu', 'Narva', 'Pärnu', 1),
('Was ist die Hauptstadt von Litauen?', 'Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai', 1),
('Was ist die Hauptstadt von Lettland?', 'Riga', 'Daugavpils', 'Jūrmala', 'Ventspils', 1),
('Wie nennt man die Hauptstadt von Dänemark?', 'Kopenhagen', 'Aarhus', 'Odense', 'Esbjerg', 1),
('In welchem Jahr wurde das erste iPhone veröffentlicht?', '2007', '2008', '2009', '2010', 1),
('Was ist die Hauptstadt von Finnland?', 'Helsinki', 'Helsingborg', 'Tampere', 'Turku', 1),
('Wie viele Zähne hat ein Mensch normalerweise?', '28', '30', '32', '34', 3),
('Was ist die Hauptstadt von Island?', 'Reykjavík', 'Akureyri', 'Kopavogur', 'Selfoss', 1),
('Was ist die Hauptstadt von Zypern?', 'Nikosia', 'Limassol', 'Larnaka', 'Famagusta', 1),
('Was ist die Hauptstadt von Malta?', 'Valletta', 'Mdina', 'Gozo', 'Sliema', 1),
('Was ist die Hauptstadt von Georgien?', 'Tiflis', 'Batumi', 'Zugdidi', 'Rustavi', 1),
('Wie nennt man die Wissenschaft von den Fischen?', 'Ichthyologie', 'Zoologie', 'Botanik', 'Biologie', 1),
('Was ist die Hauptstadt von Armenien?', 'Jerewan', 'Eriwan', 'Gyumri', 'Vanadzor', 1),
('Was ist die Hauptstadt von Aserbaidschan?', 'Baku', 'Sumqayit', 'Ganja', 'Lankaran', 1),
('Was ist die Hauptstadt von Kasachstan?', 'Nur-Sultan', 'Almaty', 'Shymkent', 'Aktobe', 1),
('Was ist die Hauptstadt von Usbekistan?', 'Taschkent', 'Samarkand', 'Bukhara', 'Nukus', 1),
('Was ist die Hauptstadt von Tadschikistan?', 'Duschanbe', 'Chudschand', 'Kuliab', 'Isfara', 1),
('Was ist die Hauptstadt von Turkmenistan?', 'Aschgabat', 'Mary', 'Balkanabat', 'Turkmenbashi', 1),
('Was ist die Hauptstadt von Kirgisistan?', 'Bischkek', 'Osch', 'Tschu', 'Naryn', 1),
('Was ist die Hauptstadt von Belarus?', 'Minsk', 'Gomel', 'Brest', 'Witebsk', 1),
('Was ist die Hauptstadt von Estland?', 'Tallinn', 'Tartu', 'Narva', 'Pärnu', 1),
('Was ist die Hauptstadt von Lettland?', 'Riga', 'Daugavpils', 'Jūrmala', 'Ventspils', 1),
('Was ist die Hauptstadt von Litauen?', 'Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai', 1),
('Was ist die Hauptstadt von Moldawien?', 'Chișinău', 'Bălți', 'Bender', 'Tighina', 1),
('Was ist die Hauptstadt von der Ukraine?', 'Kiew', 'Charkiw', 'Odessa', 'Lwiw', 1),
('Was ist die Hauptstadt von Slowenien?', 'Ljubljana', 'Maribor', 'Celje', 'Kranj', 1),
('Was ist die Hauptstadt von Kroatien?', 'Zagreb', 'Split', 'Dubrovnik', 'Rijeka', 1),
('Was ist die Hauptstadt von Serbien?', 'Belgrad', 'Novi Sad', 'Niš', 'Kragujevac', 1),
('Was ist die Hauptstadt von Albanien?', 'Tirana', 'Durrës', 'Vlorë', 'Shkodër', 1),
('Was ist die Hauptstadt von Nordmazedonien?', 'Skopje', 'Bitola', 'Ohrid', 'Kumanovo', 1),
('Was ist die Hauptstadt von Montenegro?', 'Podgorica', 'Nikšić', 'Herceg Novi', 'Bijelo Polje', 1),
('Wie nennt man die Wissenschaft von den Pflanzen?', 'Botanik', 'Zoologie', 'Biologie', 'Ökologie', 1),
('Wie viele Kontinente gibt es auf der Erde?', '5', '6', '7', '8', 2),
('Was ist die Hauptstadt von Zypern?', 'Nikosia', 'Limassol', 'Larnaka', 'Famagusta', 1),
('Wie nennt man die Hauptstadt von den Philippinen?', 'Manila', 'Cebu', 'Davao', 'Zamboanga', 1),
('Wie nennt man die Hauptstadt von Papua-Neuguinea?', 'Port Moresby', 'Lae', 'Mount Hagen', 'Madang', 1),
('Was ist die Hauptstadt von Tonga?', 'Nukualofa', 'Auckland', 'Suva', 'Honiara', 1),
('Was ist die Hauptstadt von Fidschi?', 'Suva', 'Lautoka', 'Nadi', 'Labasa', 1),
('Was ist die Hauptstadt von Samoa?', 'Apia', 'Auckland', 'Suva', 'Honiara', 1),
('Was ist die Hauptstadt von Vanuatu?', 'Port Vila', 'Luganville', 'Sola', 'Isangel', 1),
('Was ist die Hauptstadt von den Salomonen?', 'Honiara', 'Auckland', 'Suva', 'Nadi', 1),
('Wie nennt man die Hauptsprache in dem Gebiet von Hawaii?', 'Hawaiianisch', 'Englisch', 'Spanisch', 'Französisch', 1),
('Wie nennt man die Hauptstadt von Tonga?', 'Nukualofa', 'Apia', 'Suva', 'Honiara', 1),
('Wie nennt man die Hauptstadt von Neuseeland?', 'Wellington', 'Auckland', 'Christchurch', 'Hamilton', 1),
('Wie nennt man die Hauptstadt von Papua-Neuguinea?', 'Port Moresby', 'Lae', 'Mount Hagen', 'Madang', 1),
('Was ist die Hauptstadt von Kiribati?', 'Tarawa', 'Funafuti', 'South Tarawa', 'Kiritimati', 1),
('Wie nennt man die Hauptstadt von Mikronesien?', 'Palikir', 'Yap', 'Chuuk', 'Pohnpei', 1),
('Wie nennt man die Hauptstadt von den Marshallinseln?', 'Majuro', 'Ebeye', 'Maloelap', 'Jabot', 1),
('Wie nennt man die Hauptstadt von Nauru?', 'Yaren', 'Nauru', 'Aiwo', 'Boe', 1),
('Was ist die Hauptstadt von Tuvalu?', 'Funafuti', 'Nukufetau', 'Vaitupu', 'Nukulaelae', 1),
('Wie nennt man die Hauptstadt von den Vereinigten Staaten?', 'Washington, D.C.', 'New York', 'Los Angeles', 'Chicago', 1),
('Wie viele Staaten gibt es in den USA?', '50', '52', '54', '56', 1),
('Was ist die Hauptstadt von Mexiko?', 'Mexiko-Stadt', 'Guadalajara', 'Monterrey', 'Cancún', 1),
('Was ist die Hauptstadt von Guatemala?', 'Guatemala-Stadt', 'Antigua', 'Quetzaltenango', 'Escuintla', 1),
('Was ist die Hauptstadt von Costa Rica?', 'San José', 'Alajuela', 'Cartago', 'Liberia', 1),
('Was ist die Hauptstadt von Honduras?', 'Tegucigalpa', 'San Pedro Sula', 'La Ceiba', 'Choluteca', 1),
('Was ist die Hauptstadt von Nicaragua?', 'Managua', 'León', 'Granada', 'Masaya', 1),
('Was ist die Hauptstadt von El Salvador?', 'San Salvador', 'Santa Ana', 'San Miguel', 'Ahuachapán', 1),
('Wie nennt man die Hauptstadt von Panama?', 'Panama-Stadt', 'David', 'Colón', 'La Chorrera', 1),
('Wie nennt man die Hauptstadt von Kuba?', 'Havanna', 'Santiago de Cuba', 'Camagüey', 'Holguín', 1),
('Wie nennt man die Hauptstadt von Jamaika?', 'Kingston', 'Montego Bay', 'Mandeville', 'Spanish Town', 1),
('Wie nennt man die Hauptstadt von Barbados?', 'Bridgetown', 'Speightstown', 'Oistins', 'Holetown', 1),
('Was ist die Hauptstadt von Trinidad und Tobago?', 'Port of Spain', 'San Fernando', 'Scarborough', 'Point Fortin', 1),
('Wie nennt man die Hauptstadt von Guyana?', 'Georgetown', 'New Amsterdam', 'Linden', 'Anna Regina', 1),
('Wie nennt man die Hauptstadt von Suriname?', 'Paramaribo', 'Albina', 'Moengo', 'Brownsweg', 1),
('Was ist die Hauptstadt von Brasilien?', 'Brasília', 'São Paulo', 'Rio de Janeiro', 'Salvador', 2),
('Wie nennt man die Hauptstadt von Venezuela?', 'Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 1),
('Was ist die Hauptstadt von Kolumbien?', 'Bogotá', 'Medellín', 'Cali', 'Barranquilla', 1),
('Was ist die Hauptstadt von Ecuador?', 'Quito', 'Guayaquil', 'Cuenca', 'Loja', 1),
('Was ist die Hauptstadt von Peru?', 'Lima', 'Arequipa', 'Cusco', 'Trujillo', 1),
('Wie nennt man die Hauptstadt von Paraguay?', 'Asunción', 'Ciudad del Este', 'Encarnación', 'Asunción', 1),
('Was ist die Hauptstadt von Chile?', 'Santiago', 'Valparaíso', 'Concepción', 'La Serena', 1),
('Was ist die Hauptstadt von Argentinien?', 'Buenos Aires', 'Córdoba', 'Mendoza', 'Rosario', 1),
('Was ist die Hauptstadt von Uruguay?', 'Montevideo', 'Salto', 'Paysandú', 'Tacuarembó', 1),
('Was ist die Hauptstadt von Bolivien?', 'Sucre', 'La Paz', 'Cochabamba', 'Santa Cruz', 1),
('Wie nennt man die Hauptstadt von Chile?', 'Santiago', 'Valparaíso', 'Concepción', 'La Serena', 1),
('Was ist die Hauptstadt von Ecuador?', 'Quito', 'Guayaquil', 'Cuenca', 'Loja', 1),
('Was ist die Hauptstadt von Kolumbien?', 'Bogotá', 'Medellín', 'Cali', 'Barranquilla', 1),
('Was ist die Hauptstadt von Venezuela?', 'Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 1),
('Was ist die Hauptstadt von Argentinien?', 'Buenos Aires', 'Córdoba', 'Mendoza', 'Rosario', 1),
('Wie viele Zähne hat ein Mensch normalerweise?', '28', '30', '32', '34', 3),
('Wie nennt man die Hauptstadt von Australien?', 'Canberra', 'Sydney', 'Melbourne', 'Brisbane', 2),
('Wie nennt man die Hauptstadt von Japan?', 'Tokio', 'Osaka', 'Kyoto', 'Hiroshima', 1),
('Wie nennt man die Hauptstadt von Südkorea?', 'Seoul', 'Busan', 'Incheon', 'Gwangju', 1),
('Was ist die Hauptstadt von Nordkorea?', 'Pjöngjang', 'Hamhŭng', 'Namp', 'Wŏnsan', 1),
('Wie nennt man die Hauptstadt von Indien?', 'Neu-Delhi', 'Mumbai', 'Kolkata', 'Bangalore', 1),
('Was ist die Hauptstadt von Pakistan?', 'Islamabad', 'Karachi', 'Lahore', 'Peshawar', 1),
('Was ist die Hauptstadt von Bangladesch?', 'Dhaka', 'Chittagong', 'Khulna', 'Rajshahi', 1),
('Was ist die Hauptstadt von Afghanistan?', 'Kabul', 'Herat', 'Kandahar', 'Mazar-i-Sharif', 1),
('Was ist die Hauptstadt von Sri Lanka?', 'Sri Jayawardenepura Kotte', 'Colombo', 'Galle', 'Kandy', 1),
('Was ist die Hauptstadt von Nepal?', 'Kathmandu', 'Pokhara', 'Bhaktapur', 'Lalitpur', 1),
('Was ist die Hauptstadt von Bhutan?', 'Thimphu', 'Paro', 'Phuntsholing', 'Punakha', 1),
('Wie nennt man die Hauptstadt von Malediven?', 'Malé', 'Addu', 'Dhidhdhoo', 'Gan', 1),
('Wie nennt man die Hauptstadt von den Philippinen?', 'Manila', 'Cebu', 'Davao', 'Zamboanga', 1),
('Wie nennt man die Hauptstadt von Thailand?', 'Bangkok', 'Chiang Mai', 'Pattaya', 'Phuket', 1),
('Was ist die Hauptstadt von Vietnam?', 'Hanoi', 'Ho-Chi-Minh-Stadt', 'Da Nang', 'Nha Trang', 1),
('Was ist die Hauptstadt von Laos?', 'Vientiane', 'Luang Prabang', 'Pakse', 'Savannakhet', 1),
('Was ist die Hauptstadt von Kambodscha?', 'Phnom Penh', 'Siem Reap', 'Battambang', 'Sihanoukville', 1),
('Was ist die Hauptstadt von Malaysia?', 'Kuala Lumpur', 'Georgetown', 'Malacca', 'Kota Bharu', 1),
('Wie nennt man die Hauptstadt von Brunei?', 'Bandar Seri Begawan', 'Kuala Belait', 'Seria', 'Tutong', 1),
('Wie nennt man die Hauptstadt von Singapur?', 'Singapur', 'Kuala Lumpur', 'Jakarta', 'Manila', 1),
('Was ist die Hauptstadt von Myanmar?', 'Naypyidaw', 'Yangon', 'Mandalay', 'Naypyidaw', 1),
('Wie nennt man die Hauptstadt von Indien?', 'Neu-Delhi', 'Mumbai', 'Kolkata', 'Bangalore', 1),
('Was ist die Hauptstadt von Australien?', 'Canberra', 'Sydney', 'Melbourne', 'Brisbane', 2),
('Was ist die Hauptstadt von Neuseeland?', 'Wellington', 'Auckland', 'Christchurch', 'Hamilton', 1),
('Was ist die Hauptstadt von Fidschi?', 'Suva', 'Lautoka', 'Nadi', 'Labasa', 1),
('Was ist die Hauptstadt von Vanuatu?', 'Port Vila', 'Luganville', 'Sola', 'Isangel', 1),
('Wie nennt man die Hauptstadt von Tonga?', 'Nukualofa', 'Apia', 'Suva', 'Honiara', 1),
('Was ist die Hauptstadt von Samoa?', 'Apia', 'Auckland', 'Suva', 'Honiara', 1),
('Was ist die Hauptstadt von Tuvalu?', 'Funafuti', 'Nukufetau', 'Vaitupu', 'Nukulaelae', 1),
('Was ist die Hauptstadt von Kiribati?', 'Tarawa', 'Funafuti', 'South Tarawa', 'Kiritimati', 1),
('Was ist die Hauptstadt von Mikronesien?', 'Palikir', 'Yap', 'Chuuk', 'Pohnpei', 1),
('Wie nennt man die Hauptstadt von den Marshallinseln?', 'Majuro', 'Ebeye', 'Maloelap', 'Jabot', 1),
('Wie nennt man die Hauptstadt von Nauru?', 'Yaren', 'Nauru', 'Aiwo', 'Boe', 1),
('Was ist die Hauptstadt von den Vereinigten Staaten?', 'Washington, D.C.', 'New York', 'Los Angeles', 'Chicago', 1),
('Wie viele Staaten gibt es in den USA?', '50', '52', '54', '56', 1),
('Wie nennt man die Hauptstadt von Mexiko?', 'Mexiko-Stadt', 'Guadalajara', 'Monterrey', 'Cancún', 1),
('Was ist die Hauptstadt von Guatemala?', 'Guatemala-Stadt', 'Antigua', 'Quetzaltenango', 'Escuintla', 1),
('Wie nennt man die Hauptstadt von Costa Rica?', 'San José', 'Alajuela', 'Cartago', 'Liberia', 1),
('Was ist die Hauptstadt von Honduras?', 'Tegucigalpa', 'San Pedro Sula', 'La Ceiba', 'Choluteca', 1),
('Was ist die Hauptstadt von Nicaragua?', 'Managua', 'León', 'Granada', 'Masaya', 1),
('Was ist die Hauptstadt von El Salvador?', 'San Salvador', 'Santa Ana', 'San Miguel', 'Ahuachapán', 1),
('Wie nennt man die Hauptstadt von Panama?', 'Panama-Stadt', 'David', 'Colón', 'La Chorrera', 1),
('Wie nennt man die Hauptstadt von Kuba?', 'Havanna', 'Santiago de Cuba', 'Camagüey', 'Holguín', 1),
('Wie nennt man die Hauptstadt von Jamaika?', 'Kingston', 'Montego Bay', 'Mandeville', 'Spanish Town', 1),
('Wie nennt man die Hauptstadt von Barbados?', 'Bridgetown', 'Speightstown', 'Oistins', 'Holetown', 1),
('Was ist die Hauptstadt von Trinidad und Tobago?', 'Port of Spain', 'San Fernando', 'Scarborough', 'Point Fortin', 1),
('Wie nennt man die Hauptstadt von Guyana?', 'Georgetown', 'New Amsterdam', 'Linden', 'Anna Regina', 1),
('Wie nennt man die Hauptstadt von Suriname?', 'Paramaribo', 'Albina', 'Moengo', 'Brownsweg', 1),
('Was ist die Hauptstadt von Brasilien?', 'Brasília', 'São Paulo', 'Rio de Janeiro', 'Salvador', 2),
('Wie nennt man die Hauptstadt von Venezuela?', 'Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 1),
('Was ist die Hauptstadt von Kolumbien?', 'Bogotá', 'Medellín', 'Cali', 'Barranquilla', 1),
('Was ist die Hauptstadt von Ecuador?', 'Quito', 'Guayaquil', 'Cuenca', 'Loja', 1),
('Was ist die Hauptstadt von Peru?', 'Lima', 'Arequipa', 'Cusco', 'Trujillo', 1),
('Wie nennt man die Hauptstadt von Paraguay?', 'Asunción', 'Ciudad del Este', 'Encarnación', 'Asunción', 1),
('Was ist die Hauptstadt von Chile?', 'Santiago', 'Valparaíso', 'Concepción', 'La Serena', 1),
('Was ist die Hauptstadt von Argentinien?', 'Buenos Aires', 'Córdoba', 'Mendoza', 'Rosario', 1),
('Was ist die Hauptstadt von Uruguay?', 'Montevideo', 'Salto', 'Paysandú', 'Tacuarembó', 1),
('Was ist die Hauptstadt von Bolivien?', 'Sucre', 'La Paz', 'Cochabamba', 'Santa Cruz', 1);