-- Create the database
CREATE DATABASE IF NOT EXISTS who_wants_to_be_a_millionaire;

-- Switch to the new database
USE who_wants_to_be_a_millionaire;

-- Set the character set for the connection
SET NAMES 'utf8mb4';

-- Erstelle die Tabelle highscore mit nur der Spalte stage
CREATE TABLE highscore (
    stage INT NOT NULL
);

-- Füge einen Eintrag hinzu, bei dem stage 0 ist
INSERT INTO highscore (stage) VALUES (0);

-- Create the table for the questions
CREATE TABLE IF NOT EXISTS Questions (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Question TEXT NOT NULL,
    AnswerOption1 VARCHAR(255) NOT NULL,
    AnswerOption2 VARCHAR(255) NOT NULL,
    AnswerOption3 VARCHAR(255) NOT NULL,
    AnswerOption4 VARCHAR(255) NOT NULL,
    Solution INT NOT NULL CHECK (Solution IN (1, 2, 3, 4)),
	DifficultyLevel INT NOT NULL CHECK (DifficultyLevel BETWEEN 1 AND 15)
);

INSERT INTO Questions (Question, AnswerOption1, AnswerOption2, AnswerOption3, AnswerOption4, Solution, DifficultyLevel) VALUES
-- Fragen für Schwierigkeitsgrad 1 (einfach)
('Was ist die Hauptstadt von Deutschland?', 'Berlin', 'München', 'Frankfurt', 'Hamburg', 1, 1),
('Wie viele Kontinente gibt es?', '5', '6', '7', '8', 3, 1),
('Was ist die Farbe des Himmels?', 'Blau', 'Grün', 'Rot', 'Gelb', 1, 1),
('Welches Tier ist bekannt als der König der Tiere?', 'Tiger', 'Löwe', 'Bär', 'Elefant', 2, 1),
('Was ist die kleinste Einheit des Lebens?', 'Zelle', 'Molekül', 'Atom', 'Organ', 1, 1),
('Wie viele Planeten gibt es in unserem Sonnensystem?', '8', '9', '7', '10', 1, 1),
('Was essen Schildkröten?', 'Fleisch', 'Fisch', 'Pflanzen', 'Insekten', 3, 1),
('Was ist der Hauptbestandteil von Wasser?', 'Sauerstoff', 'Wasserstoff', 'Kohlenstoff', 'Stickstoff', 2, 1),
('Was ist der größte Planet im Sonnensystem?', 'Erde', 'Mars', 'Jupiter', 'Venus', 3, 1),
('Was ist die Hauptstadt von Frankreich?', 'Paris', 'Lyon', 'Marseille', 'Toulouse', 1, 1),
('Wie viele Bundesländer hat Deutschland?', '14', '15', '16', '17', 3, 1),
('Welches ist das größte Tier der Welt?', 'Blauwal', 'Elefant', 'Giraffe', 'Weißer Hai', 1, 1),
('Was ist die Farbe einer Banane?', 'Grün', 'Rot', 'Gelb', 'Blau', 3, 1),
('Was ist die Hauptstadt von Spanien?', 'Madrid', 'Barcelona', 'Valencia', 'Sevilla', 1, 1),
('Wie viele Tage hat ein Jahr?', '365', '366', '364', '370', 1, 1),
('Was ist der längste Fluss der Welt?', 'Amazonas', 'Nil', 'Yangtze', 'Mississippi', 2, 1),
('Was ist die Hauptstadt von Deutschland?', 'Berlin', 'München', 'Hamburg', 'Frankfurt', 1, 1),
('Wie viele Kontinente gibt es?', '5', '6', '7', '8', 3, 1),
('Was ist die größte Stadt in Deutschland?', 'Berlin', 'München', 'Köln', 'Frankfurt', 1, 1),
('Welcher Planet ist der Erde am nächsten?', 'Mars', 'Venus', 'Merkur', 'Jupiter', 2, 1),
('Was ist das kleinste Kontinent?', 'Asien', 'Afrika', 'Europa', 'Australien', 4, 1),
('Was ist die Farbe von Bananen?', 'Rot', 'Gelb', 'Grün', 'Blau', 2, 1),
('Wie viele Tage hat ein Jahr?', '365', '360', '366', '350', 1, 1),
('Was ist der höchste Berg der Welt?', 'K2', 'Mount Everest', 'Kilimandscharo', 'Aconcagua', 2, 1),
('Wie viele Monate hat ein Jahr?', '10', '11', '12', '13', 3, 1),
('Wie nennt man die Hauptstadt von Frankreich?', 'Berlin', 'Madrid', 'Rom', 'Paris', 4, 1),
('Was ist 5 + 5?', '10', '11', '12', '9', 1, 1),
('Was ist die Hauptsprache in Deutschland?', 'Deutsch', 'Französisch', 'Englisch', 'Spanisch', 1, 1),
('Wie viele Kontinente gibt es?', '4', '6', '7', '5', 3, 1),
('Was ist die am häufigsten gesprochene Sprache der Welt?', 'Englisch', 'Mandarin', 'Spanisch', 'Französisch', 2, 1),
('Was ist das Symbol für Wasser?', 'H2O', 'CO2', 'O2', 'N2', 1, 1),
('Wie heißt die größte Wüste der Welt?', 'Gobi', 'Kalahari', 'Sahara', 'Antarktis', 3, 1),
('Wie viele Augen hat ein Mensch?', '1', '2', '3', '4', 2, 1),
('Welches Tier ist bekannt als „König der Tiere“?', 'Tiger', 'Elefant', 'Löwe', 'Bär', 3, 1),
('Wie heißt die größte Insel der Welt?', 'Grönland', 'Neuguinea', 'Borneo', 'Madagaskar', 1, 1),
('Was ist die Hauptwährung in den USA?', 'Euro', 'Dollar', 'Pfund', 'Yen', 2, 1),
('Wie viele Tasten hat ein Klavier?', '84', '88', '90', '92', 2, 1),

-- Fragen für Schwierigkeitsgrad 2 (einfach)
('Wie nennt man einen Wasserfall?', 'Strom', 'Fluss', 'Cascade', 'Riviera', 3, 2),
('Was ist der größte Kontinent?', 'Afrika', 'Asien', 'Europa', 'Nordamerika', 2, 2),
('Was sind die Farben der deutschen Flagge?', 'Rot, Blau, Gelb', 'Rot, Schwarz, Gold', 'Schwarz, Gold, Weiß', 'Grün, Weiß, Blau', 2, 2),
('Was ist die Währung in Japan?', 'Yen', 'Dollar', 'Euro', 'Won', 1, 2),
('Wer ist der Autor von „Harry Potter“?', 'Tolkien', 'Rowling', 'Lewis', 'Austen', 2, 2),
('Wie viele Finger hat ein Mensch?', '5', '6', '7', '8', 1, 2),
('Was ist das Nationaltier von Kanada?', 'Bär', 'Wolfs', 'Luchs', 'Biber', 4, 2),
('Was ist die häufigste Farbe in der Natur?', 'Grün', 'Braun', 'Blau', 'Schwarz', 1, 2),
('Wie heißt die Hauptstadt von Australien?', 'Sydney', 'Melbourne', 'Canberra', 'Brisbane', 3, 2),
('Was ist der Hauptbestandteil von Luft?', 'Sauerstoff', 'Kohlenstoffdioxid', 'Stickstoff', 'Helium', 3, 2),
('Wie viele Zähne hat ein Erwachsener?', '28', '30', '32', '34', 3, 2),
('Welches Element hat das chemische Symbol „He“?', 'Helium', 'Wasserstoff', 'Argon', 'Neon', 1, 2),
('In welchem Jahr begann der Erste Weltkrieg?', '1912', '1914', '1916', '1918', 2, 2),
('Wie viele Monate hat ein Jahr?', '10', '11', '12', '13', 3, 2),
('Was ist der längste Fluss in Europa?', 'Rhein', 'Donau', 'Wolga', 'Elbe', 3, 2),
('Was ist die größte Stadt der USA?', 'Los Angeles', 'New York', 'Chicago', 'Houston', 2, 2),
('Wie viele Finger hat ein Mensch?', '8', '9', '10', '11', 3, 2),
('Was ist die am häufigsten vorkommende Farbe in der Natur?', 'Blau', 'Grün', 'Rot', 'Gelb', 2, 2),
('Wie viele Beine hat ein Insekt?', '4', '6', '8', '10', 2, 2),
('Was ist die Hauptstadt von Italien?', 'Rom', 'Mailand', 'Florenz', 'Venedig', 1, 2),
('Wie heißt der Hauptcharakter in „Harry Potter“?', 'Ron', 'Hermine', 'Harry', 'Dumbledore', 3, 2),
('Was ist die Währung in Japan?', 'Yen', 'Dollar', 'Euro', 'Pfund', 1, 2),
('Was ist die Hauptstadt von Spanien?', 'Madrid', 'Barcelona', 'Valencia', 'Sevilla', 1, 2),
('Was ist das Hauptnahrungsmittel in vielen asiatischen Ländern?', 'Brot', 'Reis', 'Teigwaren', 'Kartoffeln', 2, 2),
('Welches Tier ist das größte auf der Erde?', 'Afrikanischer Elefant', 'Blauwal', 'Giraffe', 'Nashorn', 2, 2),
('Was ist das Gegenteil von „heiß“?', 'Warm', 'Kalt', 'Lauwarm', 'Temperiert', 2, 2),
('Wie viele Zähne hat ein erwachsener Mensch normalerweise?', '28', '30', '32', '34', 3, 2),
('Was ist die am häufigsten gesprochene Sprache in Europa?', 'Deutsch', 'Englisch', 'Französisch', 'Spanisch', 2, 2),
('Was ist die Hauptstadt von Kanada?', 'Toronto', 'Ottawa', 'Vancouver', 'Montreal', 2, 2),
('Wie viele Herzen hat ein Oktopus?', '1', '2', '3', '4', 3, 2),
('Was ist der Hauptbestandteil von Luft?', 'Sauerstoff', 'Kohlenstoffdioxid', 'Stickstoff', 'Wasserstoff', 3, 2),
('Wie nennt man den Raum im Weltraum ohne Luft?', 'Vakuum', 'Luftloch', 'Raum', 'Nichts', 1, 2),
('Was ist die Hauptsprache in Brasilien?', 'Portugiesisch', 'Spanisch', 'Französisch', 'Englisch', 1, 2),
('Wie heißt das berühmteste Gemälde von Leonardo da Vinci?', 'Das letzte Abendmahl', 'Mona Lisa', 'Die Schule von Athen', 'Das Gebet', 2, 2),
('Was ist die Hauptstadt von Russland?', 'Moskau', 'Sankt Petersburg', 'Kiew', 'Minsk', 1, 2),

-- Fragen für Schwierigkeitsgrad 3 (einfach)
('Wer formulierte die Relativitätstheorie?', 'Isaac Newton', 'Albert Einstein', 'Niels Bohr', 'Galileo Galilei', 2, 3),
('Was ist die Hauptstadt von Kanada?', 'Toronto', 'Ottawa', 'Vancouver', 'Montreal', 2, 3),
('Was ist das chemische Symbol für Gold?', 'Au', 'Ag', 'Fe', 'Hg', 1, 3),
('Wie viele Bundesländer hat Deutschland?', '14', '15', '16', '17', 3, 3),
('Was ist das größte Raubtier der Erde?', 'Löwe', 'Tiger', 'Eisbär', 'Schwarzbär', 3, 3),
('Wie viele Herzen hat ein Oktopus?', '1', '2', '3', '4', 3, 3),
('Was ist die Hauptstadt von Indien?', 'Neu-Delhi', 'Mumbai', 'Bangalore', 'Kolkata', 1, 3),
('Wie nennt man einen Wasserkreislauf?', 'Hydrologie', 'Ozeanographie', 'Meteorologie', 'Geologie', 1, 3),
('Was ist die Geburtsstadt von Beethoven?', 'Bonn', 'Berlin', 'Wien', 'Köln', 1, 3),
('In welchem Jahr landete die erste Mondlandung?', '1961', '1969', '1971', '1965', 2, 3),
('Welcher Planet ist der Erde am nächsten?', 'Venus', 'Mars', 'Merkur', 'Jupiter', 3, 3),
('Was ist das kleinste Knochen im menschlichen Körper?', 'Säbelbein', 'Steigbügel', 'Schambein', 'Kniescheibe', 2, 3),
('Was ist die Währung in Russland?', 'Rubel', 'Dollar', 'Euro', 'Yen', 1, 3),
('Wie viele Gesichter hat ein Würfel?', '4', '5', '6', '8', 3, 3),
('Wer malte die Mona Lisa?', 'Van Gogh', 'Picasso', 'Leonardo da Vinci', 'Rembrandt', 3, 3),
('Wie lautet die chemische Formel für Wasser?', 'H2O', 'CO2', 'O2', 'NaCl', 1, 3),
('Wer schrieb „Die Verwandlung“?', 'Hermann Hesse', 'Franz Kafka', 'Thomas Mann', 'Bertolt Brecht', 2, 3),
('Was ist die Hauptstadt von Australien?', 'Sydney', 'Melbourne', 'Canberra', 'Brisbane', 3, 3),
('Wie viele Bundesländer hat Deutschland?', '14', '16', '15', '13', 2, 3),
('Was ist die größte Stadt in Afrika?', 'Nairobi', 'Lagos', 'Kairo', 'Kapstadt', 3, 3),
('Welches Element hat das chemische Symbol „O“?', 'Gold', 'Sauerstoff', 'Silber', 'Zink', 2, 3),
('Wer malte die „Sixtinische Kapelle“?', 'Raphael', 'Michelangelo', 'Da Vinci', 'Van Gogh', 2, 3),
('Was ist die Hauptstadt von Schweden?', 'Stockholm', 'Göteborg', 'Helsinki', 'Oslo', 1, 3),
('Wie viele Planeten gibt es in unserem Sonnensystem?', '7', '8', '9', '10', 2, 3),
('Was ist die größte Tierart?', 'Blauwal', 'Elefant', 'Giraffe', 'Spermawal', 1, 3),
('Wie viele Monate haben 30 Tage?', '10', '11', '12', '9', 2, 3),
('Welches Land ist für die Pyramiden bekannt?', 'Sudan', 'Ägypten', 'Iran', 'Mexiko', 2, 3),
('Wie lautet der Titel der berühmtesten Oper von Mozart?', 'Die Zauberflöte', 'Carmen', 'La Traviata', 'Tosca', 1, 3),
('Was ist der Hauptbestandteil von Zement?', 'Wasser', 'Kalkstein', 'Ton', 'Sand', 2, 3),
('Was ist die Hauptstadt von Mexiko?', 'Monterrey', 'Guadalajara', 'Mexiko-Stadt', 'Cancún', 3, 3),
('Welches Instrument hat Tasten und wird oft in der klassischen Musik verwendet?', 'Gitarre', 'Klavier', 'Geige', 'Schlagzeug', 2, 3),
('Was ist die Hauptstadt von Ägypten?', 'Alexandria', 'Kairo', 'Luxor', 'Gizeh', 2, 3),
('Was ist die chemische Formel für Kochsalz?', 'NaCl', 'KCl', 'CaCO3', 'HCl', 1, 3),
('Wie heißt die europäische Währung?', 'Dollar', 'Franken', 'Euro', 'Pfunde', 3, 3),
('Welcher Kontinent ist für seine Wüste bekannt?', 'Asien', 'Europa', 'Afrika', 'Nordamerika', 3, 3),
('Was ist das Hauptnahrungsmittel in Italien?', 'Brot', 'Pizza', 'Pasta', 'Reis', 3, 3),

-- Fragen für Schwierigkeitsgrad 4 (mittel)
('Wer war der erste Mensch im Weltraum?', 'Yuri Gagarin', 'Neil Armstrong', 'Buzz Aldrin', 'John Glenn', 1, 4),
('Wie viele Knochen hat ein erwachsener Mensch?', '206', '201', '210', '215', 1, 4),
('Was ist die chemische Formel für Natriumchlorid?', 'NaCl', 'KCl', 'CaCl2', 'LiCl', 1, 4),
('Welcher Kontinent ist für seine Pyramiden bekannt?', 'Asien', 'Afrika', 'Europa', 'Nordamerika', 2, 4),
('Was ist die Hauptstadt von Ägypten?', 'Kairo', 'Alexandria', 'Luzern', 'Cairo', 1, 4),
('Welches Element hat das chemische Symbol „Fe“?', 'Eisen', 'Gold', 'Zink', 'Kobalt', 1, 4),
('Was ist der höchste Berg der Alpen?', 'Matterhorn', 'Mont Blanc', 'Eiger', 'Kilimandscharo', 2, 4),
('Was ist die Hauptstadt von Schweden?', 'Oslo', 'Stockholm', 'Kopenhagen', 'Helsinki', 2, 4),
('Was ist die Hauptsprache in Brasilien?', 'Spanisch', 'Französisch', 'Englisch', 'Portugiesisch', 4, 4),
('In welchem Jahr wurde die Berliner Mauer gebaut?', '1961', '1975', '1959', '1989', 1, 4),
('Welches Land ist bekannt für seine Kängurus?', 'Australien', 'Neuseeland', 'Kanada', 'Indien', 1, 4),
('Was ist der größte Ozean der Erde?', 'Atlantischer Ozean', 'Indischer Ozean', 'Arktischer Ozean', 'Pazifischer Ozean', 4, 4),
('Wie viele Bundesstaaten hat die USA?', '48', '49', '50', '51', 3, 4),
('Was ist die Hauptsprache in Indien?', 'Hindi', 'Englisch', 'Tamil', 'Bengali', 1, 4),
('Was ist die Hauptstadt von Russland?', 'Moskau', 'Sankt Petersburg', 'Kasan', 'Novosibirsk', 1, 4),
('Wie viele Zeitzonen hat Russland?', '8', '9', '10', '11', 3, 4),
('Welches Land hat die größte Bevölkerung?', 'Indien', 'USA', 'China', 'Indonesien', 3, 4),
('Was ist das kleinste Land der Welt?', 'Monaco', 'Vatikanstadt', 'San Marino', 'Nauru', 2, 4),
('Was ist die Formel für die Berechnung der Fläche eines Kreises?', 'πr²', '2πr', '2πr²', 'πd', 1, 4),
('Wer schrieb „Der Prozess“?', 'Hermann Hesse', 'Franz Kafka', 'Thomas Mann', 'Friedrich Nietzsche', 2, 4),
('Was ist der längste Fluss der Welt?', 'Nil', 'Amazonas', 'Yangtze', 'Mississippi', 2, 4),
('Wie viele Tasten hat ein Klavier?', '88', '76', '90', '84', 1, 4),
('Wie viele Planeten gibt es in unserem Sonnensystem?', '9', '8', '7', '10', 2, 4),
('Was ist die Hauptstadt von Brasilien?', 'São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 3, 4),
('Wer war der erste Mensch auf dem Mond?', 'Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin', 'John Glenn', 1, 4),
('Was ist die chemische Formel für Kohlendioxid?', 'CO2', 'O2', 'H2O', 'C6H12O6', 1, 4),
('Wie viele Farben hat der Regenbogen?', '5', '6', '7', '8', 3, 4),
('Was ist die Hauptstadt von Kanada?', 'Toronto', 'Ottawa', 'Vancouver', 'Montreal', 2, 4),
('Was ist die Formel für die Berechnung der Kreisfläche?', '2πr', 'πd', 'πr²', 'd²', 3, 4),
('Was ist der Hauptbestandteil von Schokolade?', 'Zucker', 'Kakaobutter', 'Kakaopulver', 'Milch', 3, 4),
('Welcher Planet ist bekannt für seine Ringe?', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 3, 4),
('Wie heißt die größte Wüste der Welt?', 'Sahara', 'Gobi', 'Kalahari', 'Antarktis', 1, 4),
('Was ist die Hauptstadt von Frankreich?', 'Paris', 'Marseille', 'Lyon', 'Nizza', 1, 4),
('Wer komponierte die „9. Symphonie“?', 'Beethoven', 'Brahms', 'Mozart', 'Schubert', 1, 4),
('Was ist das Hauptnahrungsmittel in vielen asiatischen Ländern?', 'Reis', 'Brot', 'Teigwaren', 'Kartoffeln', 1, 4),
('Wie viele Kontinente gibt es?', '5', '6', '7', '4', 3, 4),

-- Fragen für Schwierigkeitsgrad 5 (mittel)
('Wer malte die Decke der Sixtinischen Kapelle?', 'Leonardo da Vinci', 'Michelangelo', 'Raphael', 'Donatello', 2, 5),
('Welches Land hat die meisten Vulkane?', 'Japan', 'Indonesien', 'USA', 'Italien', 2, 5),
('Was ist das kleinste Land der Welt?', 'San Marino', 'Monaco', 'Vatikanstadt', 'Liechtenstein', 3, 5),
('Welcher Roman beginnt mit „Es war die beste der Zeiten, es war die schlimmste der Zeiten“?', 'Der große Gatsby', 'Krieg und Frieden', 'Die Verwandlung', 'Eine Geschichte aus zwei Städten', 4, 5),
('Wie viele Strahlen hat der Stern auf der Flagge der USA?', '13', '50', '51', '75', 2, 5),
('Was ist die Währung in Mexiko?', 'Dollar', 'Peso', 'Euro', 'Yen', 2, 5),
('Wie viele Planeten hat unser Sonnensystem?', '7', '8', '9', '10', 2, 5),
('Wer schrieb „Die Göttliche Komödie“?', 'Dante Alighieri', 'Boccaccio', 'Petrarca', 'Machiavelli', 1, 5),
('Was ist das chemische Symbol für Wasser?', 'H2O', 'CO2', 'O2', 'H2SO4', 1, 5),
('Welches Land ist bekannt für seine Schokolade?', 'Belgien', 'Schweiz', 'Frankreich', 'Italien', 2, 5),
('Was ist die Hauptstadt von Dänemark?', 'Oslo', 'Stockholm', 'Kopenhagen', 'Helsinki', 3, 5),
('Wie heißt der größte See der Welt?', 'Eriesee', 'Baikalsee', 'Kaspisches Meer', 'Victoria-See', 3, 5),
('Was ist die größte Wüste der Welt?', 'Gobi', 'Sahara', 'Atacama', 'Kalahari', 2, 5),
('Was ist der längste Fluss in Afrika?', 'Niger', 'Nil', 'Zambezi', 'Kongo', 2, 5),
('Wie viele Staaten hat Indien?', '28', '29', '30', '31', 1, 5),
('Wie viele Sekunden hat eine Stunde?', '60', '120', '3600', '1800', 3, 5),
('Wer malte die Mona Lisa?', 'Van Gogh', 'Picasso', 'Da Vinci', 'Rembrandt', 3, 5),
('Was ist das größte Tier auf dem Land?', 'Elefant', 'Giraffe', 'Nashorn', 'Pferd', 1, 5),
('Welcher Kontinent hat die meisten Länder?', 'Afrika', 'Asien', 'Europa', 'Nordamerika', 1, 5),
('Was ist die Währung in Großbritannien?', 'Euro', 'Dollar', 'Pfund', 'Franken', 3, 5),
('Wie viele Buchstaben hat das englische Alphabet?', '24', '25', '26', '27', 3, 5),
('Was ist die chemische Formel für Methan?', 'CH4', 'CO2', 'C2H6', 'H2O', 1, 5),
('Wie viele Planeten hat das Sonnensystem?', '8', '9', '7', '6', 1, 5),
('Was ist die Hauptstadt von Italien?', 'Rom', 'Mailand', 'Florenz', 'Venedig', 1, 5),
('Wie viele Sprachen gibt es weltweit?', '2000', '7000', '5000', '3000', 2, 5),
('Welches Element hat das chemische Symbol „Au“?', 'Silber', 'Gold', 'Platin', 'Eisen', 2, 5),
('Wer war der erste Präsident der USA?', 'George Washington', 'Abraham Lincoln', 'Thomas Jefferson', 'John Adams', 1, 5),
('Wie viele Spieler hat eine Fußballmannschaft?', '10', '11', '12', '9', 2, 5),
('Was ist das am häufigsten gesprochene Wort im Deutschen?', 'ja', 'nein', 'ich', 'und', 3, 5),
('Was ist die Hauptstadt von Schweden?', 'Stockholm', 'Göteborg', 'Helsinki', 'Oslo', 1, 5),
('Was ist die größte Wüste der Welt?', 'Sahara', 'Gobi', 'Kalahari', 'Antarktis', 1, 5),
('Wie nennt man den Prozess der Umwandlung von Wasser in Dampf?', 'Kondensation', 'Verdampfung', 'Sublimation', 'Reaktion', 2, 5),
('Was ist das Hauptnahrungsmittel in vielen asiatischen Ländern?', 'Reis', 'Brot', 'Teigwaren', 'Kartoffeln', 1, 5),
('Wie viele Zähne hat ein erwachsener Mensch normalerweise?', '28', '30', '32', '34', 3, 5),
('Was ist das bekannteste Werk von Shakespeare?', 'Hamlet', 'Romeo und Julia', 'Macbeth', 'Othello', 2, 5),
('Was ist die Hauptstadt von Kanada?', 'Toronto', 'Ottawa', 'Vancouver', 'Montreal', 2, 5),

-- Fragen für Schwierigkeitsgrad 6 (mittel)
('Wer war der erste Mensch auf dem Mond?', 'Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin', 'John Glenn', 1, 6),
('Wie viele Chromosomen hat ein Mensch?', '23', '24', '46', '52', 3, 6),
('Wer entdeckte Penicillin?', 'Marie Curie', 'Louis Pasteur', 'Alexander Fleming', 'Gregor Mendel', 3, 6),
('Wie viele Elemente gibt es im Periodensystem?', '100', '118', '92', '110', 2, 6),
('Welches Land hat die größte Bevölkerung?', 'USA', 'China', 'Indien', 'Indonesien', 2, 6),
('Was ist der größte Planet im Sonnensystem?', 'Erde', 'Mars', 'Jupiter', 'Venus', 3, 6),
('In welchem Jahr wurde die Unabhängigkeitserklärung der USA unterzeichnet?', '1776', '1787', '1791', '1801', 1, 6),
('Was ist das chemische Symbol für Sauerstoff?', 'O', 'O2', 'H', 'H2', 2, 6),
('Was ist die Hauptstadt von Brasilien?', 'Sao Paulo', 'Brasilia', 'Rio de Janeiro', 'Salvador', 2, 6),
('Welches Element hat die höchste Dichte?', 'Gold', 'Platin', 'Uran', 'Quecksilber', 3, 6),
('Was ist die Währung von China?', 'Yuan', 'Dollar', 'Won', 'Euro', 1, 6),
('Wer schrieb „Der Prozess“?', 'Franz Kafka', 'Hermann Hesse', 'Thomas Mann', 'Bertolt Brecht', 1, 6),
('Was ist die Hauptstadt von Norwegen?', 'Oslo', 'Kopenhagen', 'Stockholm', 'Helsinki', 1, 6),
('Wie viele Zähne hat ein erwachsener Mensch?', '28', '30', '32', '34', 3, 6),
('Was ist die Hauptsprache in Mexiko?', 'Englisch', 'Spanisch', 'Französisch', 'Portugiesisch', 2, 6),
('Wie viele Planeten gibt es in unserem Sonnensystem?', '7', '8', '9', '10', 2, 6),
('Was ist das Hauptnahrungsmittel in China?', 'Reis', 'Brot', 'Teigwaren', 'Kartoffeln', 1, 6),
('Was ist die Hauptstadt von Japan?', 'Tokio', 'Osaka', 'Kyoto', 'Hiroshima', 1, 6),
('Wie nennt man die Wissenschaft von den Vögeln?', 'Mammologie', 'Ornithologie', 'Zoologie', 'Entomologie', 2, 6),
('Wie viele Zähne hat ein erwachsener Mensch?', '30', '32', '28', '26', 2, 6),
('Was ist die Hauptstadt von Australien?', 'Sydney', 'Canberra', 'Melbourne', 'Brisbane', 2, 6),
('Welches Element hat das chemische Symbol „Hg“?', 'Silber', 'Quecksilber', 'Gold', 'Zink', 2, 6),
('Was ist die größte Stadt in Afrika?', 'Kairo', 'Nairobi', 'Johannesburg', 'Lagos', 4, 6),
('Wie viele Kontinente gibt es?', '5', '6', '7', '4', 3, 6),
('Wer war der erste Mensch, der die Erde umrundete?', 'Ferdinand Magellan', 'Christoph Kolumbus', 'James Cook', 'Marco Polo', 1, 6),
('Was ist die am häufigsten gesprochene Sprache in der Welt?', 'Englisch', 'Mandarin', 'Spanisch', 'Französisch', 2, 6),
('Wie viele Tage hat ein Schaltjahr?', '364', '365', '366', '367', 3, 6),
('Welches Land hat die meisten Nachbarn?', 'Russland', 'China', 'Deutschland', 'USA', 2, 6),
('Was ist das größte Land der Welt?', 'Kanada', 'Russland', 'China', 'USA', 2, 6),
('Wie nennt man den Prozess der Umwandlung von Wasser in Dampf?', 'Kondensation', 'Verdampfung', 'Sublimation', 'Kühlung', 2, 6),
('Wie heißt die längste Fluss in Europa?', 'Rhein', 'Donau', 'Elbe', 'Weser', 2, 6),
('Wie nennt man die Wissenschaft von den Pilzen?', 'Mikologie', 'Botanik', 'Zoologie', 'Entomologie', 1, 6),
('Was ist das meistverkaufte Buch der Welt?', 'Die Bibel', 'Der Herr der Ringe', 'Harry Potter', 'Der Kleine Prinz', 1, 6),
('Wie nennt man das größte Tier der Welt?', 'Afrikanischer Elefant', 'Blauwal', 'Giraffe', 'Känguru', 2, 6),
('Was ist die Hauptstadt von Indien?', 'Neu-Delhi', 'Mumbai', 'Kalkutta', 'Bangalore', 1, 6),

-- Fragen für Schwierigkeitsgrad 7 (schwer)
('Wie heißt die Hauptstadt von Island?', 'Reykjavik', 'Keflavik', 'Akureyri', 'Husavik', 1, 7),
('Was ist der kleinste Knochen im menschlichen Körper?', 'Säbelbein', 'Steigbügel', 'Schambein', 'Kniescheibe', 2, 7),
('Welches Land hat die meisten Vulkane?', 'Japan', 'Indonesien', 'USA', 'Italien', 2, 7),
('In welchem Jahr begann der Zweite Weltkrieg?', '1938', '1939', '1940', '1941', 2, 7),
('Wie viele Schichten hat die Erde?', '2', '3', '4', '5', 2, 7),
('Was ist der Name des größten lebenden Tieres?', 'Eisbär', 'Blauwal', 'Afrikanischer Elefant', 'Grizzly', 2, 7),
('Wie viele Farben hat ein Regenbogen?', '5', '6', '7', '8', 3, 7),
('Wer erfand die Glühbirne?', 'Nikola Tesla', 'Albert Einstein', 'Thomas Edison', 'Alexander Graham Bell', 3, 7),
('Welches Land hat die längste Küstenlinie?', 'USA', 'Kanada', 'Australien', 'Russland', 2, 7),
('Was ist das chemische Symbol für Kohlenstoff?', 'C', 'Co', 'Ca', 'Cu', 1, 7),
('Wer ist der Hauptcharakter in „Der Hobbit“?', 'Frodo', 'Bilbo', 'Gandalf', 'Gollum', 2, 7),
('Was ist die Hauptstadt von Südkorea?', 'Seoul', 'Peking', 'Tokio', 'Bangkok', 1, 7),
('Was ist das schwerste Tier der Welt?', 'Afrikanischer Elefant', 'Blauwal', 'Giraffe', 'Killerwal', 2, 7),
('Wie viele Planeten gibt es in unserem Sonnensystem?', '8', '9', '7', '10', 1, 7),
('Welcher Planet hat die meisten Ringe?', 'Jupiter', 'Saturn', 'Uranus', 'Neptun', 2, 7),
('Wie viele Bundesländer hat Deutschland?', '15', '16', '14', '12', 2, 7),
('Welches Land hat die größte Fläche?', 'Kanada', 'Russland', 'USA', 'China', 2, 7),
('Was ist die Hauptstadt von Neuseeland?', 'Wellington', 'Auckland', 'Christchurch', 'Hamilton', 1, 7),
('Wer entdeckte Amerika?', 'Christoph Kolumbus', 'Ferdinand Magellan', 'James Cook', 'Marco Polo', 1, 7),
('Was ist die chemische Formel für Ozon?', 'O2', 'O3', 'CO2', 'H2O', 2, 7),
('Wie heißt die Hauptstadt von Griechenland?', 'Athen', 'Thessaloniki', 'Kreta', 'Korfu', 1, 7),
('Was ist die größte Stadt in Australien?', 'Sydney', 'Melbourne', 'Brisbane', 'Perth', 1, 7),
('Wer malte das berühmte Gemälde „Das letzte Abendmahl“?', 'Picasso', 'Van Gogh', 'Da Vinci', 'Monet', 3, 7),
('Wie viele Augen hat eine Biene?', '2', '3', '4', '5', 3, 7),
('Was ist die Hauptstadt von Südkorea?', 'Seoul', 'Busan', 'Incheon', 'Gwangju', 1, 7),
('Was ist das am häufigsten vorkommende Element im Universum?', 'Sauerstoff', 'Kohlenstoff', 'Wasserstoff', 'Helium', 3, 7),
('Wie viele Meter sind in einem Kilometer?', '100', '500', '1000', '1500', 3, 7),
('Was ist der Unterschied zwischen einem Amphibium und einem Reptil?', 'Lebensraum', 'Fortpflanzung', 'Atmung', 'Ernährung', 1, 7),
('Was ist die chemische Formel für Kochsalz?', 'NaCl', 'KCl', 'HCl', 'CO2', 1, 7),
('Wie nennt man die Lehre von den Tieren?', 'Botanik', 'Zoologie', 'Mikrobiologie', 'Ökologie', 2, 7),
('Wie viele Zähne hat ein erwachsener Mensch normalerweise?', '28', '30', '32', '34', 3, 7),
('Was ist die Hauptstadt von Dänemark?', 'Kopenhagen', 'Odense', 'Aarhus', 'Aalborg', 1, 7),
('Was ist die größte Stadt in Asien?', 'Peking', 'Tokio', 'Mumbai', 'Seoul', 2, 7),
('Was ist die Einheit für Energie?', 'Joule', 'Kilowatt', 'Watt', 'Newton', 1, 7),
('Wie viele Ringe sind im Olympischen Logo?', '4', '5', '6', '7', 2, 7),

-- Fragen für Schwierigkeitsgrad 8 (schwer)
('Was ist die größte Wüste der Erde?', 'Gobi', 'Sahara', 'Atacama', 'Kalahari', 2, 8),
('Wer war der erste Präsident der USA?', 'George Washington', 'Thomas Jefferson', 'Abraham Lincoln', 'Franklin D. Roosevelt', 1, 8),
('In welchem Jahr wurde die Europäische Union gegründet?', '1990', '1992', '2000', '1989', 2, 8),
('Was ist die Hauptsprache in Ägypten?', 'Arabisch', 'Französisch', 'Englisch', 'Türkisch', 1, 8),
('Wie heißt der größte Wasserfall der Welt?', 'Victoriafälle', 'Niagarafälle', 'Angel Falls', 'Iguazu', 3, 8),
('Welches ist das am häufigsten vorkommende Element im Universum?', 'Kohlenstoff', 'Sauerstoff', 'Wasserstoff', 'Helium', 3, 8),
('Wie heißt die Hauptstadt von Finnland?', 'Oslo', 'Helsinki', 'Stockholm', 'Kopenhagen', 2, 8),
('Wer war der Komponist der „Neunten Symphonie“?', 'Mozart', 'Beethoven', 'Brahms', 'Haydn', 2, 8),
('In welchem Jahr fand die erste Mondlandung statt?', '1965', '1967', '1969', '1971', 3, 8),
('Was ist die größte Stadt in Kanada?', 'Vancouver', 'Toronto', 'Montreal', 'Ottawa', 2, 8),
('Wie nennt man die wissenschaftliche Studie des Lebens?', 'Biologie', 'Ökologie', 'Anatomie', 'Genetik', 1, 8),
('Welcher Planet ist als „Roter Planet“ bekannt?', 'Mars', 'Venus', 'Merkur', 'Jupiter', 1, 8),
('Was ist die Hauptstadt von Südafrika?', 'Pretoria', 'Kapstadt', 'Johannesburg', 'Durban', 1, 8),
('Was ist die Anzahl der Zähne eines Erwachsenen?', '28', '30', '32', '34', 3, 8),
('Wie viele Erdteile gibt es?', '5', '6', '7', '8', 3, 8),
('Wer war der erste Bundeskanzler der Bundesrepublik Deutschland?', 'Konrad Adenauer', 'Willy Brandt', 'Helmut Kohl', 'Angela Merkel', 1, 8),
('Wie heißt die chemische Formel für Ammoniak?', 'NH4', 'NH3', 'N2H4', 'N2', 2, 8),
('Wie viele Chromosomen hat ein Mensch?', '46', '44', '48', '50', 1, 8),
('Was ist die Hauptstadt von Island?', 'Reykjavik', 'Akureyri', 'Kopavogur', 'Egilsstadir', 1, 8),
('Was ist die größte Wüste der Welt?', 'Sahara', 'Gobi', 'Antarktis', 'Kalahari', 3, 8),
('Was ist die Hauptstadt von Finnland?', 'Helsinki', 'Helsingborg', 'Turku', 'Espoo', 1, 8),
('Wie viele Beine hat eine Spinne?', '6', '8', '10', '12', 2, 8),
('Wer ist der Autor von „Der Prozess“?', 'Hermann Hesse', 'Franz Kafka', 'Thomas Mann', 'Friedrich Nietzsche', 2, 8),
('Wie viele Kontinente gibt es?', '6', '7', '8', '9', 2, 8),
('Was ist die chemische Formel für Wasser?', 'H2O', 'O2', 'CO2', 'H2O2', 1, 8),
('Was ist die Hauptstadt von Ägypten?', 'Kairo', 'Alexandria', 'Gizeh', 'Luxor', 1, 8),
('Wie viele Planeten gibt es in unserem Sonnensystem?', '7', '8', '9', '10', 2, 8),
('Was ist das größte Land der Welt?', 'Russland', 'Kanada', 'USA', 'China', 1, 8),
('Was ist das Hauptnahrungsmittel in Italien?', 'Pasta', 'Pizza', 'Reis', 'Brot', 1, 8),
('Was ist die größte Stadt in Indien?', 'Mumbai', 'Delhi', 'Bangalore', 'Kolkata', 2, 8),
('Was ist die Hauptstadt von Saudi-Arabien?', 'Riad', 'Dschidda', 'Dhahran', 'Mekka', 1, 8),
('Wie heißt die berühmteste Oper von Verdi?', 'Aida', 'La Traviata', 'Rigoletto', 'Otello', 1, 8),
('Was ist die chemische Formel für Essigsäure?', 'C2H4O2', 'CH3COOH', 'C2H6O2', 'C2H2O2', 2, 8),
('Was ist das bekannteste Werk von Goethes?', 'Faust', 'Die Wahlverwandtschaften', 'Die Leiden des jungen Werther', 'Wilhelm Meisters Lehrjahre', 1, 8),
('Wie nennt man die Wissenschaft der Gesteine?', 'Mineralogie', 'Geologie', 'Petrologie', 'Paleontologie', 3, 8),

-- Fragen für Schwierigkeitsgrad 9 (schwer)
('Was ist das teuerste Material der Welt?', 'Gold', 'Diamant', 'Platin', 'Uran', 2, 9),
('Wie nennt man die Bewegung der Erde um die Sonne?', 'Rotation', 'Revolution', 'Orbit', 'Ellipsen', 2, 9),
('Was ist die Hauptsprache in Argentinien?', 'Englisch', 'Spanisch', 'Portugiesisch', 'Französisch', 2, 9),
('Wie heißt der größte Ozean der Welt?', 'Atlantischer Ozean', 'Indischer Ozean', 'Arktischer Ozean', 'Pazifischer Ozean', 3, 9),
('Was ist die chemische Formel für Kohlenstoffdioxid?', 'CO2', 'O2', 'H2O', 'CH4', 1, 9),
('Wer ist bekannt für seine Theorie der natürlichen Selektion?', 'Darwin', 'Lamarck', 'Mendel', 'Newton', 1, 9),
('Was ist die Hauptstadt von Venezuela?', 'Caracas', 'Bogotá', 'Lima', 'Santiago', 1, 9),
('In welchem Jahr endete der Zweite Weltkrieg?', '1944', '1945', '1946', '1947', 2, 9),
('Wie viele Planeten hat das Sonnensystem?', '8', '9', '10', '11', 1, 9),
('Wie heißt das berühmte Gemälde von Edvard Munch?', 'Der Kuss', 'Der Schrei', 'Die Schule von Athen', 'Mona Lisa', 2, 9),
('Was ist die häufigste Krankheit der Welt?', 'Diabetes', 'Krebs', 'Hauterkrankungen', 'Erkältung', 3, 9),
('Was ist das am meisten gesprochene Wort in der Welt?', 'Ja', 'Hallo', 'Nein', 'Bitte', 1, 9),
('Wie viele Zähne hat ein normaler Mensch?', '28', '30', '32', '34', 3, 9),
('Was ist die Hauptstadt von Nigeria?', 'Lagos', 'Abuja', 'Kano', 'Port Harcourt', 2, 9),
('Was ist das schnellste Landtier?', 'Löwe', 'Gepard', 'Tiger', 'Pferd', 2, 9),
('Wie nennt man das Hauptorgan des menschlichen Körpers?', 'Herz', 'Lunge', 'Gehirn', 'Leber', 3, 9),
('Was ist die chemische Formel für Kohlensäure?', 'H2O', 'CO2', 'H2CO3', 'H2SO4', 3, 9),
('Was ist die Hauptstadt von Kroatien?', 'Zagreb', 'Split', 'Dubrovnik', 'Rijeka', 1, 9),
('Wie viele Zähne hat ein erwachsener Mensch?', '28', '30', '32', '34', 3, 9),
('Was ist das größte Tier der Welt?', 'Blauwal', 'Elefant', 'Giraffe', 'Nashorn', 1, 9),
('Wie heißt die Hauptstadt von Ägypten?', 'Kairo', 'Alexandria', 'Gizeh', 'Luxor', 1, 9),
('Was ist das am häufigsten vorkommende Element im Universum?', 'Sauerstoff', 'Kohlenstoff', 'Wasserstoff', 'Helium', 3, 9),
('Was ist die chemische Formel für Ozon?', 'O2', 'O3', 'CO2', 'H2O', 2, 9),
('Was ist die größte Stadt in Asien?', 'Peking', 'Tokio', 'Seoul', 'Bangkok', 2, 9),
('Was ist die Hauptstadt von Ungarn?', 'Budapest', 'Sofia', 'Prag', 'Krakau', 1, 9),
('Wie nennt man die Wissenschaft von den Fischen?', 'Ichthyologie', 'Zoologie', 'Mikrobiologie', 'Ökologie', 1, 9),
('Was ist die chemische Formel für Glukose?', 'C6H12O6', 'C12H22O11', 'C2H6O', 'C2H4O2', 1, 9),
('Wie nennt man die Lehre von den Pflanzen?', 'Botanik', 'Zoologie', 'Mikrobiologie', 'Ökologie', 1, 9),
('Was ist die chemische Formel für Methan?', 'CH4', 'CO2', 'C2H6', 'H2O', 1, 9),
('Wie viele Chromosomen hat ein Mensch?', '46', '44', '48', '50', 1, 9),
('Was ist die Hauptstadt von Ägypten?', 'Kairo', 'Alexandria', 'Luxor', 'Gizeh', 1, 9),
('Was ist die größte Wüste der Welt?', 'Sahara', 'Gobi', 'Kalahari', 'Antarktis', 1, 9),
('Wie viele Beine hat eine Spinne?', '6', '8', '10', '12', 2, 9),
('Was ist die chemische Formel für Wasser?', 'H2O', 'O2', 'H2O2', 'CO2', 1, 9),

-- Fragen für Schwierigkeitsgrad 10 (schwer)
('Was ist die höchste Erhebung der Welt?', 'K2', 'Kilimandscharo', 'Everest', 'Makalu', 3, 10),
('Wer erfand das Telefon?', 'Einstein', 'Bell', 'Edison', 'Tesla', 2, 10),
('Wie heißt der längste Fluss der Welt?', 'Amazonas', 'Nil', 'Yangtze', 'Mississippi', 1, 10),
('Was ist die Hauptstadt von Australien?', 'Sydney', 'Canberra', 'Melbourne', 'Brisbane', 2, 10),
('Was ist die chemische Formel für Wasser?', 'H2O', 'O2', 'H2', 'CO2', 1, 10),
('In welchem Jahr wurde die Berliner Mauer errichtet?', '1961', '1989', '1971', '1975', 1, 10),
('Wie viele Planeten gibt es im Sonnensystem?', '8', '9', '10', '7', 1, 10),
('Was ist die Hauptsprache in Indonesien?', 'Indonesisch', 'Englisch', 'Malay', 'Chinesisch', 1, 10),
('Was ist die Hauptstadt von Mexiko?', 'Guadalajara', 'Mexico City', 'Monterrey', 'Tijuana', 2, 10),
('Wer ist der Hauptcharakter in „1984“ von George Orwell?', 'Winston Smith', 'John Doe', 'Gandalf', 'Frodo', 1, 10),
('Welches Element hat das chemische Symbol „Na“?', 'Kalium', 'Natrium', 'Lithium', 'Calcium', 2, 10),
('Was ist die Hauptstadt von Griechenland?', 'Athen', 'Thessaloniki', 'Kreta', 'Rhodos', 1, 10),
('Wie nennt man den Prozess, bei dem Wasser in Dampf umgewandelt wird?', 'Verdampfung', 'Kondensation', 'Sublimation', 'Kochen', 1, 10),
('Wie heißt die berühmte Statue in Rio de Janeiro?', 'Christus der Erlöser', 'Freiheitsstatue', 'David', 'Venus von Milo', 1, 10),
('Wer war der erste Mensch, der den Südpol erreichte?', 'Roald Amundsen', 'Robert Falcon Scott', 'Ernest Shackleton', 'Matthew Henson', 1, 10),
('Was ist die am weitesten verbreitete Sprache der Welt?', 'Mandarin', 'Spanisch', 'Englisch', 'Hindi', 1, 10),
('Wie viele Planeten gibt es in unserem Sonnensystem?', '8', '9', '7', '10', 1, 10),
('Was ist die Hauptstadt von Nordkorea?', 'Seoul', 'Pyongyang', 'Busan', 'Incheon', 2, 10),
('Wer entdeckte die Relativitätstheorie?', 'Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Niels Bohr', 2, 10),
('Was ist die chemische Formel für Schwefelsäure?', 'H2SO4', 'H2O', 'CO2', 'H2S', 1, 10),
('Was ist die größte Stadt der Welt?', 'Tokio', 'Shanghai', 'Delhi', 'New York', 1, 10),
('Wie viele Spieler sind in einer Basketballmannschaft?', '4', '5', '6', '7', 2, 10),
('Was ist das am häufigsten vorkommende Element in der Erdkruste?', 'Sauerstoff', 'Silizium', 'Aluminium', 'Eisen', 2, 10),
('Was ist die Hauptstadt von Nicaragua?', 'Managua', 'Tegucigalpa', 'Havanna', 'San Salvador', 1, 10),
('Wie nennt man die Wissenschaft von den Pilzen?', 'Mikologie', 'Botanik', 'Zoologie', 'Entomologie', 1, 10),
('Wie viele Tasten hat ein Klavier?', '76', '84', '88', '90', 3, 10),
('Wer war der erste Mensch im Weltraum?', 'Yuri Gagarin', 'Neil Armstrong', 'Buzz Aldrin', 'John Glenn', 1, 10),
('Was ist die Hauptstadt von Nigeria?', 'Lagos', 'Abuja', 'Port Harcourt', 'Kano', 2, 10),
('Was ist die chemische Formel für Salzsäure?', 'HCl', 'NaCl', 'KCl', 'H2SO4', 1, 10),
('Was ist die größte Wüste der Welt?', 'Sahara', 'Antarktis', 'Gobi', 'Kalahari', 2, 10),
('Wie viele Spieler sind in einer Fußballmannschaft?', '10', '11', '12', '9', 2, 10),
('Was ist die Hauptstadt von Zypern?', 'Nikosia', 'Limassol', 'Larnaka', 'Famagusta', 1, 10),
('Was ist die chemische Formel für Ammoniak?', 'NH4', 'NH3', 'N2H4', 'N2', 2, 10),
('Was ist die größte Stadt in Europa?', 'London', 'Berlin', 'Paris', 'Madrid', 1, 10),
('Was ist das am häufigsten gesprochene Wort im Englischen?', 'the', 'and', 'is', 'to', 1, 10),

-- Fragen für Schwierigkeitsgrad 11 (schwer)
('Wer entdeckte die Relativitätstheorie?', 'Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Stephen Hawking', 2, 11),
('Was ist die Hauptstadt von Australien?', 'Canberra', 'Sydney', 'Melbourne', 'Brisbane', 1, 11),
('Welcher Planet hat die meisten Monde?', 'Jupiter', 'Saturn', 'Neptun', 'Uranus', 2, 11),
('Was ist die chemische Formel für Wasser?', 'H2O', 'CO2', 'O2', 'H2SO4', 1, 11),
('Wie viele Tasten hat ein Klavier?', '84', '88', '90', '92', 2, 11),
('Wer war der erste Mensch auf dem Mond?', 'Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin', 'John Glenn', 1, 11),
('Welches Land ist das größte der Welt?', 'USA', 'Russland', 'China', 'Kanada', 2, 11),
('Was ist die Hauptstadt von Schweden?', 'Kopenhagen', 'Oslo', 'Stockholm', 'Helsinki', 3, 11),
('Wie viele Planeten hat unser Sonnensystem?', '7', '8', '9', '10', 1, 11),
('Wie heißt das chemische Element mit dem Symbol „Hg“?', 'Gold', 'Quecksilber', 'Silber', 'Eisen', 2, 11),
('Was ist das Hauptmaterial in Stahl?', 'Kohle', 'Eisen', 'Aluminium', 'Kupfer', 2, 11),
('Was ist die höchste Erhebung in Nordamerika?', 'Denali', 'Mount Everest', 'Mount McKinley', 'Mount Logan', 1, 11),
('Wer schrieb „Krieg und Frieden“?', 'Dostojewski', 'Tolstoi', 'Gorki', 'Tschechow', 2, 11),
('Wie viele Farben hat die Flagge von Frankreich?', '1', '2', '3', '4', 3, 11),
('Was ist der Hauptbestandteil von menschlichem Haar?', 'Eiweiß', 'Zucker', 'Fett', 'Wasser', 1, 11),
('Was ist die chemische Formel für Calciumcarbonat?', 'CaCO3', 'CaO', 'CaSO4', 'Ca(OH)2', 1, 11),
('Was ist die Hauptstadt von Estland?', 'Tallinn', 'Riga', 'Vilnius', 'Helsinki', 1, 11),
('Wer entdeckte Penicillin?', 'Louis Pasteur', 'Alexander Fleming', 'Robert Koch', 'Joseph Lister', 2, 11),
('Wie viele Kontinente gibt es?', '6', '7', '8', '5', 2, 11),
('Was ist die größte Insel der Welt?', 'Grönland', 'Neuguinea', 'Borneo', 'Madagaskar', 1, 11),
('Was ist die chemische Formel für Phosphorsäure?', 'H3PO4', 'H3PO3', 'H2PO4', 'HPO3', 1, 11),
('Was ist die Hauptstadt von Malaysia?', 'Kuala Lumpur', 'Singapur', 'Jakarta', 'Bangkok', 1, 11),
('Wie viele Nerven hat der Mensch?', '100', '250', '200', '400', 3, 11),
('Wer malte die Sixtinische Kapelle?', 'Raphael', 'Michelangelo', 'Da Vinci', 'Botticelli', 2, 11),
('Was ist das am häufigsten vorkommende Element im menschlichen Körper?', 'Kohlenstoff', 'Sauerstoff', 'Wasserstoff', 'Stickstoff', 2, 11),
('Was ist die chemische Formel für Zitronensäure?', 'C6H8O7', 'C6H10O7', 'C6H12O6', 'C6H5OH', 1, 11),
('Wie nennt man die Wissenschaft von den Bakterien?', 'Mikrobiologie', 'Zoologie', 'Botanik', 'Mikologie', 1, 11),
('Was ist die Hauptstadt von Südsudan?', 'Juba', 'Khartum', 'Nairobi', 'Addis Abeba', 1, 11),
('Wie viele Knochen hat ein Erwachsener?', '206', '208', '210', '212', 1, 11),
('Was ist die chemische Formel für Ethanol?', 'C2H5OH', 'C2H6O', 'C2H4O2', 'C2H6', 1, 11),
('Wer entdeckte die Struktur der DNA?', 'James Watson', 'Francis Crick', 'Rosalind Franklin', 'Linus Pauling', 1, 11),
('Was ist die chemische Formel für Glukose?', 'C6H12O6', 'C12H22O11', 'C2H6O', 'C2H4O2', 1, 11),
('Was ist die größte Stadt in der Welt?', 'Tokio', 'Shanghai', 'New York', 'Delhi', 2, 11),
('Wie viele Chromosomen hat ein Mensch?', '46', '48', '44', '50', 1, 11),

-- Fragen für Schwierigkeitsgrad 12 (sehr schwer)
('Wie viele Dimensionen hat das Universum?', '1', '2', '3', '4', 4, 12),
('Wer ist der Autor von „Der Prozess“?', 'Dostojewski', 'Kafka', 'Tolstoi', 'Hesse', 2, 12),
('Was ist das chemische Symbol für Platin?', 'Pt', 'Pl', 'P', 'Pb', 1, 12),
('Was ist die Hauptsprache in der Schweiz?', 'Französisch', 'Deutsch', 'Italienisch', 'Rätoromanisch', 3, 12),
('Wer entdeckte das Penicillin?', 'Louis Pasteur', 'Alexander Fleming', 'Robert Koch', 'Marie Curie', 2, 12),
('Wie viele Kontinente gibt es?', '5', '6', '7', '8', 3, 12),
('Was ist die größte Stadt in Afrika?', 'Kairo', 'Johannesburg', 'Lagos', 'Nairobi', 3, 12),
('Was ist der höchste Berg der Erde?', 'Mount Everest', 'K2', 'Kilimandscharo', 'Aconcagua', 1, 12),
('Wie viele Tasten hat ein Klavier?', '84', '88', '90', '92', 2, 12),
('Wie nennt man die Wissenschaft von den Tieren?', 'Botanik', 'Zoologie', 'Ökologie', 'Anthropologie', 2, 12),
('Wie viele Nervenzellen hat das menschliche Gehirn?', '100 Millionen', '1 Billion', '10 Billionen', '50 Billionen', 3, 12),
('Wer schrieb „Die unendliche Geschichte“?', 'Hesse', 'Ende', 'Mann', 'Bachmann', 2, 12),
('Was ist die Hauptstadt von Ägypten?', 'Kairo', 'Alexandria', 'Luxor', 'Aswan', 1, 12),
('Was ist die Hauptsprache in Nigeria?', 'Englisch', 'Französisch', 'Hausa', 'Igbo', 1, 12),
('Was ist die am weitesten verbreitete Religion in der Welt?', 'Buddhismus', 'Islam', 'Christentum', 'Hinduismus', 3, 12),
('Wie viele Elemente gibt es im Periodensystem?', '100', '118', '120', '115', 2, 12),
('Wer war der erste Mensch im Weltraum?', 'Yuri Gagarin', 'John Glenn', 'Neil Armstrong', 'Buzz Aldrin', 1, 12),
('Was ist die chemische Formel für DNA?', 'C15H31O16N5P', 'C10H13N5O3', 'C5H10N5O4P', 'C22H28N10O14P2', 1, 12),
('Was ist die Hauptstadt von Armenien?', 'Jerewan', 'Baku', 'Tiflis', 'Eriwan', 1, 12),
('Wie viele Planeten gibt es in unserem Sonnensystem?', '9', '8', '7', '6', 2, 12),
('Wer entdeckte das Penicillin?', 'Louis Pasteur', 'Alexander Fleming', 'Robert Koch', 'Joseph Lister', 2, 12),
('Was ist die chemische Formel für Methan?', 'CH4', 'C2H6', 'C3H8', 'C4H10', 1, 12),
('Was ist die größte Stadt in Nordamerika?', 'New York', 'Toronto', 'Los Angeles', 'Chicago', 1, 12),
('Was ist die chemische Formel für Kaliumpermanganat?', 'KMnO4', 'K2Cr2O7', 'K2SO4', 'K2MnO4', 1, 12),
('Wie viele Chromosomen hat ein Mensch?', '46', '44', '48', '50', 1, 12),
('Wer war der erste Präsident der USA?', 'George Washington', 'Thomas Jefferson', 'Abraham Lincoln', 'Franklin D. Roosevelt', 1, 12),
('Wie viele Nerven hat der Mensch?', '100', '250', '200', '400', 3, 12),
('Was ist die chemische Formel für Ozon?', 'O3', 'O2', 'O', 'H2O', 1, 12),
('Was ist die Hauptstadt von Aserbaidschan?', 'Baku', 'Jerewan', 'Tiflis', 'Tashkent', 1, 12),
('Was ist die chemische Formel für Essigsäure?', 'CH3COOH', 'C2H4O2', 'C2H6O', 'C3H6O3', 1, 12),
('Was ist die Hauptstadt von Kasachstan?', 'Nur-Sultan', 'Almaty', 'Astana', 'Shymkent', 1, 12),
('Wer ist der Autor von „1984“?', 'George Orwell', 'Aldous Huxley', 'Ray Bradbury', 'Fahrenheit 451', 1, 12),
('Was ist die chemische Formel für Phosphorsäure?', 'H3PO4', 'H2PO4', 'H3PO3', 'HPO3', 1, 12),
('Wer war der erste Mensch auf dem Mond?', 'Neil Armstrong', 'Yuri Gagarin', 'Buzz Aldrin', 'Michael Collins', 1, 12),

-- Fragen für Schwierigkeitsgrad 13 (sehr schwer)
('Was ist die Theorie, die die Struktur der DNA erklärt?', 'Mendel', 'Watson und Crick', 'Darwin', 'Hershey und Chase', 2, 13),
('Wie viele Chromosomen hat der Mensch?', '46', '23', '48', '44', 1, 13),
('Welches Element hat die höchste Elektronegativität?', 'Fluor', 'Sauerstoff', 'Chlor', 'Stickstoff', 1, 13),
('Wer entdeckte die radioaktive Strahlung?', 'Marie Curie', 'Albert Einstein', 'Niels Bohr', 'James Clerk Maxwell', 1, 13),
('Wie viele Moleküle hat ein Liter Wasser?', '6,02 x 10^23', '3,01 x 10^23', '1,0 x 10^24', '2,0 x 10^24', 1, 13),
('Was beschreibt die Unschärferelation?', 'Max Planck', 'Werner Heisenberg', 'Albert Einstein', 'Niels Bohr', 2, 13),
('Was ist die Hauptstadt von Bhutan?', 'Thimphu', 'Kathmandu', 'Dharamshala', 'Lhasa', 1, 13),
('Was ist der Hauptbestandteil des menschlichen Körpers?', 'Fett', 'Protein', 'Wasser', 'Mineralien', 3, 13),
('Wer ist der Vater der modernen Physik?', 'Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Max Planck', 2, 13),
('In welchem Jahr wurde das erste Element im Periodensystem entdeckt?', '1803', '1869', '1896', '1901', 2, 13),
('Welches Land hat die größte Anzahl an Inseln?', 'Schweden', 'Indonesien', 'Kanada', 'Finnland', 1, 13),
('Wer formulierte die Relativitätstheorie?', 'Newton', 'Einstein', 'Galileo', 'Planck', 2, 13),
('Was ist die Hauptsprache in Bangladesch?', 'Hindi', 'Bengalisch', 'Urdu', 'Englisch', 2, 13),
('Wie viele Zähne hat ein erwachsener Mensch?', '30', '32', '28', '34', 2, 13),
('Was ist das chemische Symbol für Gold?', 'Au', 'Ag', 'Pb', 'Fe', 1, 13),
('Wer schrieb die „Ilias“?', 'Homer', 'Virgil', 'Ovid', 'Sappho', 1, 13),
('Was ist die chemische Formel für Benzol?', 'C6H6', 'C6H12', 'C6H10', 'C6H8', 1, 13),
('Wie viele Ozeane gibt es auf der Erde?', '3', '4', '5', '6', 3, 13),
('Wer war der erste Mensch, der den Mount Everest bestiegen hat?', 'Sir Edmund Hillary', 'Reinhold Messner', 'Tenzing Norgay', 'George Mallory', 1, 13),
('Was ist die Hauptstadt von Djibouti?', 'Djibouti-Stadt', 'Addis Abeba', 'Mogadischu', 'Nairobi', 1, 13),
('Welches Element hat das chemische Symbol „Fe“?', 'Zink', 'Eisen', 'Fluor', 'Blei', 2, 13),
('Wer malte „Das letzte Abendmahl“?', 'Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Caravaggio', 2, 13),
('Wie viele Schachfiguren hat jeder Spieler zu Beginn?', '16', '14', '12', '18', 1, 13),
('Was ist die größte Fledermausart der Welt?', 'Vampirfledermaus', 'Fruchtfledermaus', 'Riesenfledermaus', 'Mexikanische Faltennase', 3, 13),
('Wer ist der Begründer der Relativitätstheorie?', 'Isaac Newton', 'Galileo Galilei', 'Albert Einstein', 'Stephen Hawking', 3, 13),
('Was ist die Hauptstadt von Tansania?', 'Dodoma', 'Dar es Salaam', 'Kigoma', 'Arusha', 1, 13),
('Welches ist das am häufigsten vorkommende Gas in der Erdatmosphäre?', 'Sauerstoff', 'Stickstoff', 'Kohlenstoffdioxid', 'Argon', 2, 13),
('Wer schrieb „Der Steppenwolf“?', 'Hermann Hesse', 'Franz Kafka', 'Thomas Mann', 'Erich Maria Remarque', 1, 13),
('Was ist das am tiefsten gelegene Punkt der Erde?', 'Challenger-Tief', 'Marianengraben', 'Totes Meer', 'Bodensee', 1, 13),
('Was ist die chemische Formel für Natriumchlorid?', 'NaCl', 'NaOH', 'KCl', 'HCl', 1, 13),
('Wie viele Zähne hat ein erwachsener Mensch normalerweise?', '28', '30', '32', '26', 3, 13),
('Wer entdeckte das Radioaktive Element Uran?', 'Marie Curie', 'Henri Becquerel', 'Ernest Rutherford', 'Lise Meitner', 1, 13),
('Was ist die Hauptstadt von Barbados?', 'Bridgetown', 'Kingston', 'Port of Spain', 'Havanna', 1, 13),
('Was ist die chemische Formel für Schwefeldioxid?', 'SO2', 'SO3', 'H2SO4', 'H2S', 1, 13),
('Was ist das am schnellsten fliegende Tier?', 'Wanderfalke', 'Schwalbe', 'Adler', 'Kolibri', 1, 13),
('Wer war der letzte Kaiser von Russland?', 'Nikolaus II.', 'Alexander III.', 'Peter der Große', 'Paul I.', 1, 13),

-- Fragen für Schwierigkeitsgrad 14 (sehr schwer)
('Wie viele Sprachen werden weltweit geschätzt gesprochen?', '2000', '7000', '5000', '3000', 2, 14),
('Was ist die Hauptursache für den Treibhauseffekt?', 'CO2-Emissionen', 'Methan', 'Ozon', 'Wasserdampf', 1, 14),
('Welcher Physiker entwickelte das Konzept der Quantenmechanik?', 'Max Planck', 'Niels Bohr', 'Werner Heisenberg', 'Richard Feynman', 1, 14),
('Was ist die Formel für die Berechnung der Energie?', 'E=mc²', 'F=ma', 'E=hv', 'PV=nRT', 1, 14),
('Welches Land hat die höchste Lebenserwartung?', 'Schweiz', 'Japan', 'Singapur', 'Norwegen', 2, 14),
('Wie heißt das berühmteste Kunstwerk von Leonardo da Vinci?', 'Das letzte Abendmahl', 'Die Geburt der Venus', 'Mona Lisa', 'Das Mädchen mit dem Perlenohrring', 3, 14),
('Was ist die Hauptstadt von Neuseeland?', 'Auckland', 'Wellington', 'Christchurch', 'Hamilton', 2, 14),
('Was ist die größte Wüste der Welt?', 'Kalahari', 'Sahara', 'Antarktis', 'Gobi', 3, 14),
('Was ist das Hauptmaterial von DNA?', 'RNA', 'Protein', 'Zucker', 'Nukleinsäuren', 4, 14),
('Was ist die am häufigsten gesprochene Sprache in der Welt?', 'Spanisch', 'Mandarin', 'Englisch', 'Hindi', 2, 14),
('Wer ist der Autor von „Der Steppenwolf“?', 'Hermann Hesse', 'Franz Kafka', 'Thomas Mann', 'Bertolt Brecht', 1, 14),
('Wie viele Zeitzonen gibt es in der Welt?', '24', '36', '12', '48', 1, 14),
('Was ist die chemische Formel für Ammoniak?', 'NH3', 'H2O', 'CO2', 'CH4', 1, 14),
('Wie heißt das größte Tier auf der Erde?', 'Blauwal', 'Afrikanischer Elefant', 'Spermawal', 'Weißer Hai', 1, 14),
('Was ist die Hauptstadt von Myanmar?', 'Bangkok', 'Yangon', 'Naypyidaw', 'Kuala Lumpur', 3, 14),
('Was ist die Hauptstadt von Burkina Faso?', 'Ouagadougou', 'Bamako', 'Nairobi', 'Accra', 1, 14),
('Wer formulierte die Gesetze der Bewegung?', 'Isaac Newton', 'Galileo Galilei', 'Albert Einstein', 'Niels Bohr', 1, 14),
('Was ist die chemische Formel für Koffein?', 'C8H10N4O2', 'C7H8N4O2', 'C6H12O6', 'C9H12N4O3', 1, 14),
('Wie viele Planeten gibt es im Sonnensystem?', '8', '9', '10', '7', 1, 14),
('Wer entdeckte die Struktur der DNA?', 'James Watson', 'Francis Crick', 'Rosalind Franklin', 'Linus Pauling', 1, 14),
('Was ist die Hauptstadt von Bosnien und Herzegowina?', 'Sarajevo', 'Zagreb', 'Belgrad', 'Podgorica', 1, 14),
('Was ist die chemische Formel für Acetylsalicylsäure?', 'C9H8O4', 'C7H6O3', 'C6H12O6', 'C10H8O4', 1, 14),
('Was ist der größte Planet in unserem Sonnensystem?', 'Jupiter', 'Saturn', 'Neptun', 'Uranus', 1, 14),
('Wer ist der Autor von „Krieg und Frieden“?', 'Leo Tolstoi', 'Fjodor Dostojewski', 'Anton Tschechow', 'Ivan Turgenev', 1, 14),
('Was ist die chemische Formel für Ethanol?', 'C2H5OH', 'C3H8O', 'C2H4O2', 'C4H10O', 1, 14),
('Wer erfand das Telefon?', 'Alexander Graham Bell', 'Thomas Edison', 'Nikola Tesla', 'Michael Faraday', 1, 14),
('Was ist die Hauptstadt von Südkorea?', 'Seoul', 'Peking', 'Tokio', 'Hanoi', 1, 14),
('Wie viele Tasten hat ein Klavier?', '88', '76', '61', '49', 1, 14),
('Was ist die größte Wüste der Welt?', 'Sahara', 'Gobi', 'Arabische Wüste', 'Antarktis', 4, 14),
('Wer malte die Mona Lisa?', 'Leonardo da Vinci', 'Vincent van Gogh', 'Pablo Picasso', 'Claude Monet', 1, 14),
('Was ist die Hauptstadt von Elfenbeinküste?', 'Yamoussoukro', 'Abidjan', 'Bouaké', 'Korhogo', 2, 14),
('Wie viele Farben hat ein Regenbogen?', '7', '6', '8', '5', 1, 14),
('Was ist die chemische Formel für Harnstoff?', 'CO(NH2)2', 'C2H5NO', 'C3H7NO', 'C4H11NO2', 1, 14),
('Wie viele Jahre dauerte der Dreißigjährige Krieg?', '30', '29', '28', '31', 1, 14),
('Was ist die Hauptstadt von Nordmazedonien?', 'Skopje', 'Zagreb', 'Sofia', 'Pristina', 1, 14),
('Was ist das am häufigsten vorkommende Element im Universum?', 'Wasserstoff', 'Helium', 'Sauerstoff', 'Kohlenstoff', 1, 14),

-- Fragen für Schwierigkeitsgrad 15 (sehr schwer)
('Was ist das kleinste Element im Periodensystem?', 'Helium', 'Wasserstoff', 'Lithium', 'Bor', 2, 15),
('Wie viele Muskeln hat der menschliche Körper?', '600', '640', '700', '800', 2, 15),
('Was ist die einzige feste Landmasse auf der Erde, die nicht Teil eines Kontinents ist?', 'Grönland', 'Australien', 'Neuseeland', 'Antarktis', 1, 15),
('Wer entdeckte die Gravitation?', 'Galileo Galilei', 'Isaac Newton', 'Albert Einstein', 'Niels Bohr', 2, 15),
('Was ist die Hauptursache für die globale Erwärmung?', 'Abholzung', 'Treibhausgase', 'Ozeanversauerung', 'Luftverschmutzung', 2, 15),
('Wer war der erste Mensch im Weltraum?', 'Neil Armstrong', 'Yuri Gagarin', 'John Glenn', 'Buzz Aldrin', 2, 15),
('Was ist die größte Spezies von Haien?', 'Tigerhai', 'Walhai', 'Hammerhai', 'Weißer Hai', 2, 15),
('Wie viele Jahre dauert ein Sonnenzyklus?', '10 Jahre', '11 Jahre', '12 Jahre', '13 Jahre', 2, 15),
('Wer malte das berühmte Gemälde „Die Nachtwache“?', 'Rembrandt', 'Vermeer', 'Van Gogh', 'Dali', 1, 15),
('Was ist die häufigste Ursache für Erdbeben?', 'Vulkanismus', 'Plattentektonik', 'Klimawandel', 'Tsunami', 2, 15),
('Was ist die Hauptsprache in Afghanistan?', 'Dari', 'Paschtu', 'Farsi', 'Arabisch', 2, 15),
('Wie viele Knochen hat der menschliche Körper?', '206', '205', '204', '207', 1, 15),
('Wer entdeckte die Struktur der DNA?', 'Francis Crick', 'James Watson', 'Rosalind Franklin', 'Avery', 1, 15),
('Was ist die am weitesten verbreitete Pflanze auf der Erde?', 'Loblolly-Kiefer', 'Wasserpflanze', 'Mais', 'Weizen', 3, 15),
('Was ist der Hauptbestandteil von Erdnussbutter?', 'Erdnüsse', 'Zucker', 'Öl', 'Salz', 1, 15),
('Was ist der Unterschied zwischen Prokaryoten und Eukaryoten?', 'Zellkern', 'Zellwand', 'DNA', 'Ribosomen', 1, 15),
('Wie viele Schichten hat die Erdkruste?', '1', '2', '3', '4', 3, 15),
('Was ist die chemische Formel für Schwefeltrioxid?', 'SO3', 'SO2', 'H2SO4', 'H2S', 1, 15),
('Wer schrieb „Der Prozess“?', 'Franz Kafka', 'Hermann Hesse', 'Thomas Mann', 'Rainer Maria Rilke', 1, 15),
('Was ist die Hauptstadt von Sri Lanka?', 'Sri Jayawardenepura Kotte', 'Colombo', 'Kandy', 'Galle', 1, 15),
('Was ist die höchste Erhebung der Erde?', 'Mount Everest', 'K2', 'Kangchenjunga', 'Lhotse', 1, 15),
('Was ist die chemische Formel für Trisäure?', 'H3PO4', 'C6H12O6', 'C6H10O5', 'C3H6O3', 1, 15),
('Was ist der größte Asteroid im Asteroidengürtel?', 'Ceres', 'Vesta', 'Pallas', 'Hygiea', 1, 15),
('Wie viele Zähne hat ein Erwachsener normalerweise?', '32', '30', '28', '34', 1, 15),
('Wer formulierte die Quantentheorie?', 'Max Planck', 'Niels Bohr', 'Albert Einstein', 'Erwin Schrödinger', 1, 15),
('Was ist die Hauptstadt von Gabun?', 'Libreville', 'Port-Gentil', 'Franceville', 'Booué', 1, 15),
('Was ist die chemische Formel für Ammoniak?', 'NH3', 'NH4', 'N2H4', 'N2O', 1, 15),
('Wie viele Töne hat eine Oktave?', '7', '12', '8', '10', 1, 15),
('Was ist die kleinste Einheit eines chemischen Elements?', 'Atom', 'Molekül', 'Ion', 'Isotop', 1, 15),
('Wie viele Planeten hat unser Sonnensystem?', '8', '9', '10', '7', 1, 15),
('Wer entdeckte das Penicillin?', 'Alexander Fleming', 'Louis Pasteur', 'Robert Koch', 'Edward Jenner', 1, 15),
('Was ist die chemische Formel für Glykol?', 'C2H6O2', 'C3H8O3', 'C4H10O4', 'C2H4O2', 1, 15),
('Was ist die Hauptstadt von Estland?', 'Tallinn', 'Riga', 'Vilnius', 'Helsinki', 1, 15),
('Wie viele Liter Blut hat ein Mensch?', '5-6', '3-4', '7-8', '9-10', 1, 15),
('Was ist die chemische Formel für Glukose?', 'C6H12O6', 'C5H10O5', 'C6H10O5', 'C7H14O7', 1, 15),
('Wer war der erste Mensch auf dem Mond?', 'Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin', 'John Glenn', 1, 15);